import type { AuthoredFact } from "../engine/types";
import { kf } from "./facts";

/** Further Key Facts units so later chapters are not a thin slice. */
export const DEPTH_FACTS: AuthoredFact[] = [
  {
    id: "m-loss-of-use",
    chapter: 1,
    section: "Loss of use",
    conceptId: "motor-loss-of-use",
    title: "Loss of use is excluded unless bought",
    kind: "exclusion",
    claim:
      "[[Loss of use]] is a specific exclusion under comprehensive motor cover, though some insurers will sell limited [[per-day]] cover for extra premium, and many will provide a replacement vehicle for a limited period.",
    importance: "supporting",
    skill: "know",
    sources: [kf(1, "Loss of use", "9"), kf(1, "Comprehensive", "7")],
    prerequisites: ["motor-comp"],
    confusedWith: ["motor-breakdown"],
    teachBackCue: "Is loss of use standard comprehensive cover?",
  },
  {
    id: "m-glass-ncd",
    chapter: 1,
    section: "Breakage of glass",
    conceptId: "motor-glass",
    title: "Glass claims and NCD",
    kind: "rule",
    claim:
      "Glass breakage is [[standard under comprehensive]] and can be added to non-comprehensive for extra premium. A payment under this section [[alone does not affect NCD]].",
    importance: "core",
    skill: "understand",
    sources: [kf(1, "Breakage of glass", "8–9")],
    prerequisites: ["motor-ncd"],
    confusedWith: ["motor-ncd"],
  },
  {
    id: "m-elections",
    chapter: 1,
    section: "Elections",
    conceptId: "motor-elections",
    title: "Election use of vehicles",
    kind: "rule",
    claim:
      "Using a vehicle for [[elections]] may fall outside normal [[social, domestic and pleasure]] use. Insurers do not usually charge extra except for [[parliamentary elections]].",
    importance: "detail",
    skill: "know",
    sources: [kf(1, "Elections", "10")],
    prerequisites: ["motor-use"],
  },
  {
    id: "m-racing",
    chapter: 1,
    section: "Racing, competitions, rallies and trials",
    conceptId: "motor-racing",
    title: "Rallies vs racing",
    kind: "distinction",
    claim:
      "[[Road safety rallies]] may be covered at no extra charge. Events involving [[racing]] are covered only by a few specialist insurers, and then usually for extra premium.",
    importance: "supporting",
    skill: "understand",
    sources: [kf(1, "Racing, competitions, rallies and trials", "11")],
    confusedWith: ["motor-use"],
  },
  {
    id: "m-caravans",
    chapter: 1,
    section: "Caravans and trailers",
    conceptId: "motor-caravans",
    title: "Caravans attached vs separate",
    kind: "cover",
    claim:
      "Insurers generally give [[third party]] cover for caravans or trailers [[while attached]] to the insured vehicle. Wider caravan cover is usually a [[separate non-motor policy]]; trailer comprehensive cover may be an extension.",
    importance: "supporting",
    skill: "know",
    sources: [kf(1, "Caravans and trailers", "11")],
    confusedWith: ["motor-commercial-trailers"],
  },
  {
    id: "m-pa-ext",
    chapter: 1,
    section: "Personal accident benefits",
    conceptId: "motor-pa-extension",
    title: "Motor personal accident extension",
    kind: "cover",
    claim:
      "The motor PA extension can increase [[capital (lump sum) benefits]] or add [[weekly benefits]] for the insured or spouse, and may include rehabilitation such as physiotherapy or MRI.",
    importance: "detail",
    skill: "know",
    sources: [kf(1, "Personal accident benefits", "9")],
    prerequisites: ["motor-comp-benefits"],
    confusedWith: ["health-pas"],
  },
  {
    id: "m-cycle-specified",
    chapter: 1,
    section: "Motorcycle insurance",
    conceptId: "motor-cycle-specified",
    title: "Specified motorcycle insurance",
    kind: "definition",
    claim:
      "The single method of insuring motorcycles is [[specified motorcycle insurance]]: the driver is insured for a [[particular motorcycle]]. ‘Motorcycle’ includes mechanically propelled cycles such as mopeds.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Motorcycle insurance", "13")],
    prerequisites: ["motor-cycle"],
  },
  {
    id: "h-benefit-not-indemnity",
    chapter: 2,
    section: "Personal accident and sickness",
    conceptId: "health-pas-benefit",
    title: "PA is a benefit contract",
    kind: "distinction",
    claim:
      "A personal accident and sickness policy is [[not a contract of indemnity]]. It is a [[benefit policy]]: it pays a sum on a stated contingency, not measured by financial loss. Weekly benefit is still kept to around [[normal earnings]] so there is no inducement to stay off work.",
    extra: "Occupation is the main rating factor for the accident element, not for sickness. Insurers group occupations into four classes for accident risk.",
    importance: "core",
    skill: "understand",
    sources: [kf(2, "Personal accident and sickness", "17–18")],
    confusedWith: ["health-medexp"],
    teachBackCue: "Why is PA/sickness not indemnity, yet weekly benefit is still capped near earnings?",
  },
  {
    id: "h-accident-def",
    chapter: 2,
    section: "Accident cover",
    conceptId: "health-pas-accident",
    title: "Accident must be fortuitous",
    kind: "definition",
    claim:
      "Accident cover pays for accidental death or bodily injury from an [[identifiable, fortuitous]] cause, usually with a time limit from the accident to the specified event, and often [[independently of any other cause]].",
    importance: "core",
    skill: "understand",
    sources: [kf(2, "Accident cover", "18")],
    prerequisites: ["health-pas"],
  },
  {
    id: "h-sickness-21",
    chapter: 2,
    section: "Sickness cover",
    conceptId: "health-pas-sickness",
    title: "First 21 days of sickness",
    kind: "exclusion",
    claim:
      "Sickness cover generally excludes sickness [[contracted within the first 21 days]] of the policy, so the insurer is not paying for disease already incubating at inception. Weekly benefit can run up to [[104 weeks]] of total disablement from usual occupation.",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Sickness cover", "19")],
    prerequisites: ["health-pas-franchise"],
    confusedWith: ["health-pas-franchise"],
  },
  {
    id: "h-ptd",
    chapter: 2,
    section: "Permanent total disablement",
    conceptId: "health-ptd",
    title: "Permanent total disablement",
    kind: "definition",
    claim:
      "[[Permanent total disablement]] is usually a [[capital sum]] (IF2 illustrates say £20,000+), often not payable until [[12 or 24 months]] after the accident so permanence and totality can be judged. Less commonly a ten-year annuity is used.",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Permanent total disablement", "18"), kf(2, "Permanent total disablement", "20")],
    confusedWith: ["health-ppd", "health-ttd"],
  },
  {
    id: "h-ppd",
    chapter: 2,
    section: "Permanent partial disablement",
    conceptId: "health-ppd",
    title: "Permanent partial is not standard",
    kind: "distinction",
    claim:
      "[[Permanent partial disablement]] is [[not a standard]] PA benefit. When given, it pays for loss of specified parts of limbs (toes, fingers) at a smaller percentage than loss of a whole limb.",
    importance: "supporting",
    skill: "understand",
    sources: [kf(2, "Permanent partial disablement", "20")],
    confusedWith: ["health-ptd"],
  },
  {
    id: "h-ttd",
    chapter: 2,
    section: "Temporary total disablement",
    conceptId: "health-ttd",
    title: "Temporary total disablement",
    kind: "definition",
    claim:
      "[[Temporary total disablement]] is inability to engage in one’s [[usual occupation]] due to accident or sickness, paid as a [[weekly benefit]] (IF2 illustrates at least about £100 per week in related discussion of partial).",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Temporary total disablement", "20")],
    confusedWith: ["health-tpd", "health-ptd"],
  },
  {
    id: "h-tpd",
    chapter: 2,
    section: "Temporary partial disablement",
    conceptId: "health-tpd",
    title: "Temporary partial disablement",
    kind: "definition",
    claim:
      "[[Temporary partial disablement]] prevents attending to a [[substantial part]] of normal business due to [[accident]] (not sickness). Traditional weekly amount is about [[40% of TTD]], though a different figure can be requested if justified.",
    importance: "supporting",
    skill: "understand",
    sources: [kf(2, "Temporary partial disablement", "21")],
    confusedWith: ["health-ttd", "health-ppd"],
  },
  {
    id: "h-death-12",
    chapter: 2,
    section: "Death",
    conceptId: "health-death-window",
    title: "Death within twelve months",
    kind: "rule",
    claim:
      "Insurers often require death to occur [[within twelve months]] of the event giving rise to the claim. Capital benefits can start from about [[£20,000]] in the Key Facts illustration.",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Death", "19")],
    prerequisites: ["health-pas-benefits"],
  },
  {
    id: "h-mei",
    chapter: 2,
    section: "Medical expenses insurance",
    conceptId: "health-mei",
    title: "Medical expenses insurance vs NHS",
    kind: "definition",
    claim:
      "[[Medical expenses insurance]] (also called health care insurance) pays for [[private medical treatment outside the NHS]]. Inpatient cover typically includes hospital charges (theatre, dressings, consultations) and specialist fees (surgeons, anaesthetists).",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Medical expenses insurance", "23")],
    confusedWith: ["health-medexp"],
    teachBackCue: "How does MEI differ from the modest medical expenses add-on on a PA policy?",
  },
  {
    id: "h-geo",
    chapter: 2,
    section: "Geographical limits",
    conceptId: "health-pas-geo",
    title: "Accident vs sickness geography",
    kind: "distinction",
    claim:
      "Accident cover is usually [[worldwide]] (sometimes restricted). Sickness cover is generally [[UK, Europe, USA, Canada, Australia and New Zealand]], extendable beyond those limits for extra premium.",
    importance: "supporting",
    skill: "know",
    sources: [kf(2, "Geographical limits", "21")],
    prerequisites: ["health-pas-limits"],
  },
  {
    id: "p-acc-damage",
    chapter: 3,
    section: "Accidental damage extension",
    conceptId: "hh-accidental-damage",
    title: "Household accidental damage extension",
    kind: "cover",
    claim:
      "Many insurers offer a household [[accidental damage]] extension at a higher rate, always with an excess of at least [[£100]] (often more). Example: drilling through a pipe.",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Accidental damage extension", "30")],
    prerequisites: ["hh-buildings"],
    confusedWith: ["hh-all-risks"],
  },
  {
    id: "p-contents-limits",
    chapter: 3,
    section: "Contents insurance",
    conceptId: "hh-contents-limits",
    title: "Contents single-article limits",
    kind: "rule",
    claim:
      "Contents perils largely match buildings, but there are [[limits on single articles of value]]. Specified high-value items taken away from the home are usually insured on an [[all risks]] basis with a separate sum insured above a threshold (IF2 illustrates e.g. £1,500).",
    importance: "core",
    skill: "understand",
    sources: [kf(3, "Contents insurance", "31"), kf(3, "Personal possessions", "33")],
    prerequisites: ["hh-contents"],
    confusedWith: ["hh-possessions"],
  },
  {
    id: "p-shop",
    chapter: 3,
    section: "Commercial insurance",
    conceptId: "package-shop",
    title: "Shop and hotel packages",
    kind: "cover",
    claim:
      "Commercial packages are available for most [[shopkeepers and hoteliers]] and other specified trades. The [[fabric of the building]] is generally insured or rated [[separately]] because the package is geared to the business contents and liabilities, not the structure.",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Commercial insurance", "43")],
    prerequisites: ["package-commercial"],
  },
  {
    id: "p-travel-med",
    chapter: 3,
    section: "Travel insurance",
    conceptId: "hh-travel-medical",
    title: "Travel medical and trip length",
    kind: "cover",
    claim:
      "Travel insurance commonly covers medical treatment, extra hotel/travelling expenses, bringing the patient home, and additional expenses of the party. A medical sum insured of [[£10 million]] is not uncommon. Single-trip cover is usually a maximum of [[three months]]; annual multi-trip exists for regular travellers.",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Travel insurance", "39–40")],
    prerequisites: ["hh-travel"],
  },
  {
    id: "pr-standard-fire",
    chapter: 4,
    section: "Fire and special perils",
    conceptId: "prop-fire-wording",
    title: "DAMAGE in capital letters",
    kind: "definition",
    claim:
      "The ABI [[Standard Fire and Special Perils Policy (Material Damage)]] uses [[DAMAGE]] in capitals to mean loss or destruction of or damage to the property insured. Standard fire is a defined set of perils, not ‘anything that happens’.",
    importance: "core",
    skill: "understand",
    sources: [kf(4, "Fire and special perils", "47")],
    prerequisites: ["prop-fire"],
    confusedWith: ["prop-all-risks"],
  },
  {
    id: "pr-holdup",
    chapter: 4,
    section: "Theft insurance",
    conceptId: "prop-holdup",
    title: "Hold-up vs forcible theft",
    kind: "distinction",
    claim:
      "[[Hold-up]] is theft accompanied by [[assault or violence, or the threat of it]], to the insured or employees, whether or not there is forcible entry. It is an [[extension]], not automatic in a forcible-and-violent theft wording.",
    importance: "core",
    skill: "understand",
    sources: [kf(4, "Theft insurance", "56")],
    prerequisites: ["prop-theft"],
    confusedWith: ["prop-theft"],
    scenario: {
      setup: "A shop assistant is threatened with a knife at the counter; the door was unlocked.",
      question: "Is this standard theft (force and violence to the premises) or hold-up?",
      answer: "Hold-up — violence or threat to people, irrespective of forcible entry.",
    },
  },
  {
    id: "pr-all-risks",
    chapter: 4,
    section: "All risks",
    conceptId: "prop-all-risks",
    title: "All risks vs named perils",
    kind: "distinction",
    claim:
      "The [[Standard All Risks Policy (Material Damage)]] covers [[accidental loss or destruction or damage]], subject to exclusions. Fire and special perils instead offers a [[choice of named perils]], each with its own exclusions.",
    importance: "core",
    skill: "understand",
    sources: [kf(4, "All risks", "53")],
    confusedWith: ["prop-fire", "hh-all-risks"],
    teachBackCue: "What is the structural difference between all risks and fire & special perils?",
  },
  {
    id: "pr-engineering",
    chapter: 4,
    section: "Engineering",
    conceptId: "prop-engineering",
    title: "Engineering as a property class",
    kind: "cover",
    claim:
      "Engineering is treated as its own property class in the Key Facts map of chapter 4. Business interruption may be written on an engineering basis; some engineering perils are not usually available under ordinary material-damage fire wordings.",
    extra:
      "IF2 lists engineering alongside fire/special perils and all risks as a common BI policy type (chapter 5), and as a property heading in chapter 4.",
    importance: "supporting",
    skill: "know",
    sources: [kf(4, "Engineering", "47"), kf(5, "Engineering", "69–70")],
    prerequisites: ["prop-fire"],
  },
  {
    id: "pr-money-pa",
    chapter: 4,
    section: "Money insurance",
    conceptId: "prop-money-pa",
    title: "Money personal accident extension",
    kind: "cover",
    claim:
      "A typical money-policy extension is [[personal accident]] compensation for assault in connection with money. [[Credit cards]] are not covered by a standard money policy and need their own extension.",
    importance: "supporting",
    skill: "know",
    sources: [kf(4, "Optional extensions", "61")],
    prerequisites: ["prop-money"],
    confusedWith: ["health-pas"],
  },
  {
    id: "pr-money-7day",
    chapter: 4,
    section: "Exclusions",
    conceptId: "prop-money-fidelity",
    title: "Employee dishonesty on money",
    kind: "exclusion",
    claim:
      "Money insurance typically excludes loss due to the [[dishonesty of an employee]] not discovered within [[seven days]]. That employee-fraud risk is the territory of [[fidelity]] cover, not the money all-risks section.",
    importance: "core",
    skill: "understand",
    sources: [kf(4, "Exclusions", "61")],
    prerequisites: ["prop-money"],
    confusedWith: ["pec-fidelity"],
  },
  {
    id: "pe-group-sections",
    chapter: 5,
    section: "Group legal benefit policies",
    conceptId: "pec-legal-group-sections",
    title: "Four group legal sections",
    kind: "cover",
    claim:
      "Group legal benefit policies let the proposer choose among four sections: [[employment]], [[personal]], [[motor]], and [[conveyancing]] cover.",
    importance: "supporting",
    skill: "know",
    sources: [kf(5, "Group legal benefit policies", "64")],
    prerequisites: ["pec-legal-group"],
  },
  {
    id: "pe-comm-legal",
    chapter: 5,
    section: "Commercial legal protection policies",
    conceptId: "pec-legal-commercial",
    title: "Commercial legal sections",
    kind: "cover",
    claim:
      "Commercial legal protection typically offers five choosable sections including [[employment]] (unfair dismissal / discrimination defence and awards), [[criminal]] (including HSW), [[property disputes]], [[motor]], and [[patents/registered designs]] (not all insurers).",
    extra:
      "It does not cover disputes that are the subject of public liability, nor actions the insured pursues without reasonable prospects as the Key Facts limitations describe.",
    importance: "core",
    skill: "understand",
    sources: [kf(5, "Commercial legal protection policies", "65")],
    prerequisites: ["pec-legal"],
    confusedWith: ["pl-cover"],
  },
  {
    id: "pe-declaration",
    chapter: 5,
    section: "Basis of fixing sums insured",
    conceptId: "pec-bi-declaration",
    title: "Declaration-linked BI",
    kind: "procedure",
    claim:
      "A [[declaration linked]] BI policy only requires an estimate for the forthcoming year. Insurers then apply a [[one-third uplift]] so the insured need not project as far ahead as a full indemnity-period multiple.",
    importance: "core",
    skill: "understand",
    sources: [kf(5, "Basis of fixing sums insured", "68")],
    prerequisites: ["pec-bi-sum"],
    confusedWith: ["pec-bi-sum"],
  },
  {
    id: "pe-turnover",
    chapter: 5,
    section: "Turnover",
    conceptId: "pec-bi-turnover",
    title: "Turnover in BI",
    kind: "definition",
    claim:
      "[[Turnover]] is the total income arising from the activities of the business. BI has two dimensions: the [[maximum indemnity period]] chosen by the insured, and the sum insured built from turnover and standing charges.",
    importance: "core",
    skill: "know",
    sources: [kf(5, "Turnover", "67"), kf(5, "Basic features", "67")],
    prerequisites: ["pec-bi"],
  },
  {
    id: "pe-fidelity",
    chapter: 5,
    section: "Fidelity",
    conceptId: "pec-fidelity",
    title: "Fidelity guarantee",
    kind: "cover",
    claim:
      "[[Fidelity]] (fidelity guarantee) is the pecuniary class that responds to [[employee dishonesty]] / theft of money or stock by staff — the risk money policies typically exclude if not discovered quickly.",
    importance: "core",
    skill: "understand",
    sources: [kf(5, "Fidelity", "63")],
    confusedWith: ["prop-money", "prop-theft"],
    teachBackCue: "A cashier steals over months. Which IF2 class, not theft or money, is designed for that?",
  },
  {
    id: "pe-credit",
    chapter: 5,
    section: "Credit insurance",
    conceptId: "pec-credit",
    title: "Credit insurance",
    kind: "cover",
    claim:
      "[[Credit insurance]] is a pecuniary class covering the insured against customers failing to pay trade debts — distinct from legal expenses (cost of pursuing rights) and from BI (loss of income after insured damage).",
    importance: "supporting",
    skill: "know",
    sources: [kf(5, "Credit insurance", "63")],
    confusedWith: ["pec-legal", "pec-bi"],
  },
  {
    id: "l-elto",
    chapter: 6,
    section: "Employers’ liability insurance",
    conceptId: "el-elto",
    title: "ELTO replaced the EL service",
    kind: "procedure",
    claim:
      "The EL tracing service (1999) was replaced in [[2011]] by the [[Employers’ Liability Tracing Office (ELTO)]], an independent not-for-profit industry body with a database of EL policies for claimants. From April 2012 the FCA required relevant firms to use it.",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Employers’ liability insurance", "74–75")],
    prerequisites: ["el-compulsory"],
  },
  {
    id: "l-ern",
    chapter: 6,
    section: "Employers’ liability insurance",
    conceptId: "el-ern",
    title: "Employer reference number",
    kind: "rule",
    claim:
      "Employers must give insurers their [[employer reference number (ERN)]]. Each ERN is unique; even if the employer moves tax office the historic ERN for a point in time is permanent. ELTO uses the ERN as the identifier; insurers must supply it to the ELD.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Employers’ liability insurance", "75")],
    prerequisites: ["el-elto"],
  },
  {
    id: "l-employee-def",
    chapter: 6,
    section: "Definition of employee",
    conceptId: "el-employee",
    title: "Who is an employee for EL",
    kind: "definition",
    claim:
      "An employee is [[any person under a contract of service or apprenticeship]] with the insured. Injury must arise [[out of and in the course of]] employment in the trade or business. Cover is typically [[occurrence]] during the period of insurance, not claims-made.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Definition of employee", "76"), kf(6, "Period of insurance", "77")],
    prerequisites: ["el-cover"],
    confusedWith: ["do-cover"],
  },
  {
    id: "l-pl-conseq",
    chapter: 6,
    section: "Public liability insurance",
    conceptId: "pl-consequential",
    title: "PL consequential and financial loss",
    kind: "cover",
    claim:
      "Public liability covers accidental injury and physical damage to third party property, plus [[consequential loss flowing from that damage]]. Separate [[financial loss]] cover (loss not following physical damage) is a narrower, often optional, idea — not the same as BI.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Consequential loss", "80"), kf(6, "Financial loss", "80")],
    prerequisites: ["pl-cover"],
    confusedWith: ["pec-bi", "products-cover"],
  },
  {
    id: "l-products-agg",
    chapter: 6,
    section: "Product liability insurance",
    conceptId: "products-aggregate",
    title: "Products yearly aggregate",
    kind: "rule",
    claim:
      "Product liability usually specifies a [[yearly aggregate]] limit applying to all injury and damage in the period, often the same figure as any one occurrence. Sellers of goods (manufacturers, retailers) need this class.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Product liability insurance", "82")],
    prerequisites: ["products-cover"],
  },
  {
    id: "l-pi-claims",
    chapter: 6,
    section: "Professional indemnity",
    conceptId: "pi-claims-made",
    title: "PI is claims-made",
    kind: "rule",
    claim:
      "Professional indemnity, like D&O, is typically [[claims-made]]: it protects against civil liability for professional negligence when the claim is made, not when the advice was given, subject to retroactive dates.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Professional indemnity", "88")],
    prerequisites: ["pi-cover"],
    confusedWith: ["el-cover", "pl-cover"],
  },
  {
    id: "l-el-min-limit",
    chapter: 6,
    section: "Employers’ liability insurance",
    conceptId: "el-compulsory",
    title: "EL statutory minimum and market practice",
    kind: "limit",
    claim:
      "The Employers’ Liability (Compulsory Insurance) Regulations [[1998]] raised the statutory minimum EL limit from £2 million to [[£5 million]]. In practice insurers have provided a [[£10 million]] limit since January [[1995]].",
    extra:
      "This is a different £10 million from public liability’s ‘not uncommon’ occurrence limit. EL is the compulsory class (with motor third party). PL is not.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Employers’ liability insurance", "73")],
    confusedWith: ["pl-cover"],
    mcq: {
      stem: "What is the statutory minimum limit of indemnity under employers’ liability insurance following the 1998 Regulations, as stated in the IF2 Key Facts?",
      options: ["£2 million", "£5 million", "£10 million", "Unlimited"],
      correct: 1,
      whyWrong: [
        "That was the previous statutory floor, not the 1998 figure.",
        "Correct: the 1998 Regulations raised the minimum from £2 million to £5 million.",
        "Market practice since January 1995, not the statutory minimum.",
        "EL is a limited class; injury indemnity is unlimited in motor, not here.",
      ],
    },
  },
  {
    id: "l-el-pure-accident",
    chapter: 6,
    section: "Legal liability",
    conceptId: "el-cover",
    title: "EL pays legal liability, not every workplace accident",
    kind: "distinction",
    claim:
      "An EL policy indemnifies only the employer’s [[legal liability]] to pay damages. A ‘pure’ accident with [[no negligence]] is not an EL damages claim: the employee must look to [[personal accident and sickness]] or the social security system.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Legal liability", "75")],
    confusedWith: ["health-pas", "pl-cover"],
    teachBackCue: "A workplace injury with no negligence — is that an EL claim in IF2?",
  },
  {
    id: "l-el-vicarious",
    chapter: 6,
    section: "Legal liability",
    conceptId: "el-cover",
    title: "Vicarious liability",
    kind: "rule",
    claim:
      "The employer is liable for the negligence of employees arising [[in the course of their employment]]. This is termed [[vicarious liability]], including where a fellow employee of the victim committed the negligent act.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Damages", "75–76")],
  },
  {
    id: "l-el-territorial",
    chapter: 6,
    section: "Territorial limits",
    conceptId: "el-cover",
    title: "EL territorial limits",
    kind: "limit",
    claim:
      "EL usually requires the injury to be sustained in [[Great Britain, Northern Ireland, the Isle of Man or the Channel Islands]], or while [[temporarily outside]] those territories (sometimes restricted to [[non-manual]] workers).",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Territorial limits", "77")],
  },
  {
    id: "l-el-few-exclusions",
    chapter: 6,
    section: "Limitations",
    conceptId: "el-cover",
    title: "EL has very few standard exclusions",
    kind: "exclusion",
    claim:
      "There are [[very few standard exclusions]] in an EL policy, mainly because they are not permitted by the compulsory insurance legislation. There is not even a standard [[war risks]] exclusion. Cover may still be limited by [[trade clauses]] (restricting the business, excluding kinds of work, machines or processes).",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Limitations", "78")],
    confusedWith: ["pl-cover"],
  },
  {
    id: "l-pl-exclusions",
    chapter: 6,
    section: "Public liability insurance",
    conceptId: "pl-cover",
    title: "PL exclusions that name another class",
    kind: "exclusion",
    claim:
      "Because public liability is wider than EL, it lists exclusions including [[injury to employees]], [[product liability]], [[professional negligence]], contractual liability, cost of rectifying defective work, deliberate acts, [[motor vehicles]], vessels and craft, lifts/elevators/boilers, war risks and radioactive contamination.",
    extra:
      "Injury to employees is the waiter-not-guest trap. Product liability is often bought as an extension. Professional negligence is PI.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Exclusions", "80")],
    confusedWith: ["el-cover", "products-cover", "pi-cover"],
    mcq: {
      stem: "Which of the following is a standard public liability exclusion in the IF2 Key Facts, because it belongs to another compulsory class?",
      options: [
        "Injury to members of the public",
        "Injury to employees",
        "Consequential loss flowing from damaged third-party property",
        "Claimants’ costs and expenses",
      ],
      correct: 1,
      whyWrong: [
        "Injury to the public is the open PL grant.",
        "Correct: injury to employees is listed as a PL exclusion — that is EL.",
        "PL covers consequential loss flowing from insured damage.",
        "Claimants’ costs sit with the indemnity, as with EL.",
      ],
    },
  },
  {
    id: "l-pl-extensions",
    chapter: 6,
    section: "Optional extensions",
    conceptId: "pl-cover",
    title: "Common PL optional extensions",
    kind: "cover",
    claim:
      "The two optional extensions most commonly provided on public liability are [[tenants’ liability]] and [[defective premises]].",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Optional extensions", "80")],
  },
  {
    id: "l-products-when",
    chapter: 6,
    section: "Product liability insurance",
    conceptId: "products-cover",
    title: "Products: injury during the period, not the supply date",
    kind: "rule",
    claim:
      "The injury or damage must occur [[during the period of insurance]], [[not necessarily]] when the goods or services were supplied. Financial loss is not usually covered unless it results from actual bodily injury or loss of or damage to property.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Standard policy cover", "81")],
    confusedWith: ["do-cover"],
    mcq: {
      stem: "Under a products liability policy as described in IF2, the injury or damage must occur",
      options: [
        "when the goods were supplied, even if injury is years later",
        "during the period of insurance, not necessarily when the goods were supplied",
        "only after a claim is notified, because products is always claims-made",
        "only if the buyer also holds extended warranty",
      ],
      correct: 1,
      whyWrong: [
        "Key Facts separates the supply date from the injury date.",
        "Correct.",
        "Claims-made is the D&O / PI trigger, not the products wording here.",
        "Extended warranty is the buyer’s defect product, not products liability.",
      ],
    },
  },
  {
    id: "l-products-exclusions",
    chapter: 6,
    section: "Product liability insurance",
    conceptId: "products-cover",
    title: "Products extra exclusions",
    kind: "exclusion",
    claim:
      "A products liability policy takes the public liability exclusions and also excludes [[contractual liability]], [[damage to goods supplied]], [[faulty design or formula]], and [[unsuitability or failure to perform]].",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Exclusions", "82")],
    confusedWith: ["extended-warranty"],
  },
  {
    id: "l-do-two-covers",
    chapter: 6,
    section: "Directors’ and officers’ D&O",
    conceptId: "do-cover",
    title: "D&O has two indemnities",
    kind: "cover",
    claim:
      "D&O has two elements: cover for directors and officers in their [[personal capacity]] when they cannot claim an indemnity from the company, and cover for the [[company]] where it is permitted to indemnify them (for example repayment of legal defence costs).",
    extra:
      "The Companies (Audit, Investigations and Community Enterprise) Act 2004 lets companies fund defence and indemnify certain third-party liabilities, but not the legal costs of an unsuccessful criminal defence or criminal fines and penalties.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Standard policy cover", "84"), kf(6, "Directors’ and officers’ D&O", "83")],
  },
  {
    id: "l-do-pension-offence",
    chapter: 6,
    section: "Directors’ and officers’ D&O",
    conceptId: "do-cover",
    title: "Pension Schemes Act 2021 offences",
    kind: "rule",
    claim:
      "The Pension Schemes Act [[2021]] introduced two new criminal offences relating to pension schemes. They can be committed by anyone, including a director or officer, and can lead to fines of up to [[£1 million]].",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Directors’ and officers’ D&O", "83")],
  },
  {
    id: "l-do-exclusions",
    chapter: 6,
    section: "Directors’ and officers’ D&O",
    conceptId: "do-cover",
    title: "D&O exclusions that name another class",
    kind: "exclusion",
    claim:
      "Typical D&O exclusions include prior notification, US/Canada jurisdiction clauses, [[bodily injury and property damage]], pollution, improper personal gain, fraud, [['insured v. insured']], [[breach of professional duty]] (usually PI), and fines, penalties and punitive damages.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Policy exclusions", "85")],
    confusedWith: ["pi-cover", "pl-cover"],
  },
  {
    id: "l-pi-excludes-pl",
    chapter: 6,
    section: "Professional indemnity",
    conceptId: "pi-cover",
    title: "PI is always claims-made and is not public liability",
    kind: "distinction",
    claim:
      "Professional indemnity policies, like D&O, are [[always]] on a [['claims made']] basis. Apart from excluding risks that are the subject of [[public liability]] and, possibly, claims arising outside the UK, a PI policy usually excludes [[dishonesty of the insured]].",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Professional indemnity", "85–86")],
    confusedWith: ["pl-cover", "do-cover"],
  },
  {
    id: "l-cyber-sides",
    chapter: 6,
    section: "Cyber insurance",
    conceptId: "cyber-cover",
    title: "Cyber first-party and third-party",
    kind: "cover",
    claim:
      "Cyber policies may combine [[first party]] cover (the business’s own assets) and [[third party]] cover (the assets of others). Important exclusions include [[employers’ liability]] unless data-privacy obligations have not been met, [[products liability]], fines against the public interest, and a [[time excess]] on business income that can range from 12 to 168 hours.",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Summary of covers", "90"), kf(6, "Some important exclusions", "90")],
    confusedWith: ["el-cover", "products-cover"],
  },
  {
    id: "l-ew-term",
    chapter: 6,
    section: "Extended warranties",
    conceptId: "extended-warranty",
    title: "EW extends the maker’s twelve months, often to five years",
    kind: "rule",
    claim:
      "The manufacturer’s guarantee usually covers repairs or defects for [[twelve months]]. Extended warranty is a time extension: free repairs following electrical and mechanical defects for a period of up to [[five years]]. A typical sum insured is [[£2,500]] per period. Repairs must often be carried out by the [[supplier]].",
    extra:
      "Exclusions include failure to follow the manufacturer’s instructions, risks normally covered by household contents, war, and costs of repairs to bulbs, aerials, knobs and similar.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Extended warranties", "90–91")],
    confusedWith: ["products-cover", "hh-contents"],
  },
];
