import type { AuthoredFact } from "../engine/types";
import { eg, kf, st } from "./facts";

/** Additional examinable units so Chs 1–6 are not a thin slice of the Key Facts. */
export const MORE_FACTS: AuthoredFact[] = [
  {
    id: "m-comp-extras",
    chapter: 1,
    section: "Comprehensive",
    conceptId: "motor-comp-benefits",
    title: "Typical comprehensive extras",
    kind: "cover",
    claim:
      "Comprehensive typically includes [[personal accident cover]], extra [[medical expenses]] (often about £250–£500 beyond RTA emergency treatment), and modest [[personal belongings and clothing]] (often around £250, sometimes £1,000).",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Comprehensive", "8"), st("A1D", "1/5")],
    prerequisites: ["motor-comp"],
  },
  {
    id: "m-doc-third-party",
    chapter: 1,
    section: "Comprehensive",
    conceptId: "motor-driving-other",
    title: "Driving other cars is third party only",
    kind: "rule",
    claim:
      "Even under a comprehensive private motor policy, [[driving other cars]] is only [[third party]] cover — there is [[no cover for damage to the vehicle being driven]].",
    importance: "core",
    skill: "understand",
    sources: [st("A1D", "1/4")],
    prerequisites: ["motor-comp"],
    confusedWith: ["motor-comp"],
    teachBackCue: "If you have comprehensive cover and drive a friend’s car, what happens if you damage that car?",
  },
  {
    id: "m-ncd-protect",
    chapter: 1,
    section: "No claims discount (NCD)",
    conceptId: "motor-ncd",
    title: "Protected vs guaranteed NCD",
    kind: "distinction",
    claim:
      "A [[protected]] NCD allows a modest defined number of claims without dropping the discount. A [['guaranteed' discount]] after say five claim-free years can be protected ‘for life’ at extra premium, but does [[not]] guarantee the premium from which the discount is taken.",
    importance: "supporting",
    skill: "understand",
    sources: [st("A1E", "1/5"), kf(1, "No claims discount (NCD)", "8")],
  },
  {
    id: "m-young-drivers",
    chapter: 1,
    section: "Young additional drivers",
    conceptId: "motor-young-drivers",
    title: "Young additional vs main driver",
    kind: "rule",
    claim:
      "An occasional young additional driver (say under 25) may be added for extra premium. If the young person is a [[main driver]] even without owning the car, the insurer [[rates on the young driver’s age and experience]], not the owner’s.",
    importance: "supporting",
    skill: "apply",
    sources: [kf(1, "Young additional drivers", "9"), st("A2C", "1/5–1/6")],
    scenario: {
      setup: "A parent owns the car but their 21-year-old child is one of the main drivers.",
      question: "Whose age and experience does IF2 say the insurer uses to rate?",
      answer: "The young driver’s age and experience, not the owner’s.",
    },
  },
  {
    id: "m-breakdown",
    chapter: 1,
    section: "Breakdown cover",
    conceptId: "motor-breakdown",
    title: "Breakdown is usually extra",
    kind: "cover",
    claim:
      "Breakdown assistance (call-out, limited roadside labour, towing) is typically an [[optional extra for additional premium]], not standard comprehensive cover. Recovery after an [[accident]] is treated differently from recovery after [[breakdown]].",
    importance: "supporting",
    skill: "know",
    sources: [st("A2J", "1/7"), st("Question 1.1", "1/9")],
    confusedWith: ["motor-comp"],
  },
  {
    id: "m-legal-exp-motor",
    chapter: 1,
    section: "Motor legal expenses",
    conceptId: "motor-legal-expenses",
    title: "Motor legal expenses add-on",
    kind: "cover",
    claim:
      "Motor legal expenses (when the insured is [[not to blame]]) may pay lawyers’ costs up to say [[£100,000]] to recover financial losses (excess, travel) or injury compensation from the responsible person.",
    importance: "detail",
    skill: "know",
    sources: [kf(1, "Motor legal expenses", "12"), st("A2K", "1/7")],
  },
  {
    id: "m-multi-car",
    chapter: 1,
    section: "Multi car policies",
    conceptId: "motor-multi-car",
    title: "Multi-car policies",
    kind: "cover",
    claim:
      "Multi-car policies can include several vehicles (sometimes 5 or 6) [[registered at the same address]], comprehensive or TPFT as appropriate, usually with a premium saving and [[separate NCDs]] per vehicle.",
    importance: "supporting",
    skill: "know",
    sources: [kf(1, "Multi car policies", "13"), st("A2M", "1/7")],
  },
  {
    id: "m-joint",
    chapter: 1,
    section: "Joint policies",
    conceptId: "motor-joint",
    title: "Joint motor policies",
    kind: "rule",
    claim:
      "Joint names (e.g. spouses) may operate as if [[each had their own policy]] and treat the other as a [[third party]], so one joint insured can claim against the other if at fault. Driving-other-cars is often limited to one of them.",
    importance: "detail",
    skill: "understand",
    sources: [st("A2L", "1/7")],
  },
  {
    id: "m-misfuel",
    chapter: 1,
    section: "Misfuelling",
    conceptId: "motor-misfuel",
    title: "Misfuelling",
    kind: "cover",
    claim:
      "Misfuelling extensions address loss or damage from [[accidentally filling the insured vehicle with the incorrect type of fuel]].",
    importance: "detail",
    skill: "know",
    sources: [kf(1, "Misfuelling", "13"), st("A2N", "1/7")],
  },
  {
    id: "m-exclusions-list",
    chapter: 1,
    section: "Exclusions",
    conceptId: "motor-exclusions",
    title: "General motor exclusions",
    kind: "exclusion",
    claim:
      "General exclusions include [[unlicensed drivers]], [[use outside the certificate]], contractual liability, war, radioactive/nuclear, [[riot and civil commotion in Northern Ireland for own damage]], sonic bangs, and pollution unless from a [[single identifiable event]]. Unroadworthy condition is also typical.",
    importance: "core",
    skill: "know",
    sources: [st("A3", "1/8"), kf(1, "Exclusions", "14–15")],
  },
  {
    id: "m-bike-mobility",
    chapter: 1,
    section: "Optional extensions",
    conceptId: "motor-cycle",
    title: "Invalid carriages / mobility vehicles",
    kind: "rule",
    claim:
      "Class 3 invalid carriages, mobility scooters and powered wheelchairs can be insured under motorcycle-style specialised policies. Insurance is [[recommended but not required]] (particularly for class 3).",
    importance: "detail",
    skill: "know",
    sources: [st("B2 Invalid carriages", "1/9")],
  },
  {
    id: "m-comm-load",
    chapter: 1,
    section: "Third party liability",
    conceptId: "motor-commercial-loading",
    title: "Loading and unloading",
    kind: "cover",
    claim:
      "Commercial third party liabilities extend to accidents during [[loading or unloading]]. For the driver or attendant this can extend [[beyond the carriageway]].",
    importance: "supporting",
    skill: "know",
    sources: [st("C1A", "1/11"), kf(1, "Third party liability", "17")],
    prerequisites: ["motor-commercial"],
  },
  {
    id: "m-comm-trailers",
    chapter: 1,
    section: "Trailers",
    conceptId: "motor-commercial-trailers",
    title: "Commercial trailers",
    kind: "cover",
    claim:
      "Towing of trailers is covered under [[third party liability]]. Articulated/non-articulated: third party while attached is standard; some policies give comprehensive. Disabled mechanically propelled vehicles on tow are usually [[TPO]] (no damage to the towed vehicle or its goods) though some insurers now offer comprehensive while attached.",
    importance: "supporting",
    skill: "know",
    sources: [st("C1C", "1/11"), kf(1, "Trailers", "18")],
  },
  {
    id: "m-comm-spares",
    chapter: 1,
    section: "Loss of or damage to the vehicle",
    conceptId: "motor-commercial",
    title: "Commercial spares only on the vehicle",
    kind: "distinction",
    claim:
      "Commercial comprehensive covers the vehicle and spares/accessories [[while on the vehicle]]. Unlike private motor, there is typically [[no cover while detached]] (private motor can cover them in the insured’s garage).",
    importance: "supporting",
    skill: "know",
    sources: [st("C1B", "1/11")],
  },
  {
    id: "m-comm-ext-loss-use",
    chapter: 1,
    section: "Optional extensions",
    conceptId: "motor-commercial-extensions",
    title: "Commercial optional extras",
    kind: "cover",
    claim:
      "Commercial options include increased TPPD, unusual PA/medical extras, belongings for long-distance drivers, windscreen, indemnity to hirers or principal, carnival floats, sheets and ropes (often locked compartment), loss of use up to [[80% of leasing/hire charges]], and tools in transit on comprehensive policies.",
    importance: "detail",
    skill: "know",
    sources: [st("C2", "1/12")],
  },
  {
    id: "m-foreign-green",
    chapter: 1,
    section: "Foreign use",
    conceptId: "motor-foreign",
    title: "Green card free circulation",
    kind: "rule",
    claim:
      "From [[2 August 2021]] the UK participates in the Green Card Free Circulation Area (EEA plus Andorra, Bosnia & Herzegovina, Serbia and Switzerland), removing the green-card requirement for those countries. Many insurers still issued cards until [[2 September 2021]] on MIB recommendation. Spanish bail bonds are no longer a legal requirement and most insurers have stopped them.",
    importance: "detail",
    skill: "know",
    sources: [st("A2F", "1/6"), kf(1, "Foreign use", "10")],
  },

  {
    id: "h-not-indemnity",
    chapter: 2,
    section: "Personal accident and sickness",
    conceptId: "health-pas",
    title: "Benefit not indemnity; occupation classes",
    kind: "definition",
    claim:
      "PA & sickness is a [[benefit]] contract, not indemnity. Occupation is the main rating factor for the [[accident]] element (typically four occupational classes), [[not for sickness]]. Weekly disablement is kept to no more than [[normal earnings]] so there is no inducement to stay off work; other policies must be declared.",
    importance: "core",
    skill: "understand",
    sources: [kf(2, "Personal accident and sickness insurance", "17–18")],
  },
  {
    id: "h-franchise",
    chapter: 2,
    section: "Sickness cover",
    conceptId: "health-pas-franchise",
    title: "Seven-day time franchise",
    kind: "rule",
    claim:
      "Sickness weekly benefit is usually subject to a [[seven-day time franchise]]: under seven days, [[nothing]] is paid; if sickness continues beyond seven days the claim covers the [[entire period including the first seven days]]. A franchise is a threshold, not an amount deducted like an excess. Sickness contracted in the first [[21 days]] is generally excluded.",
    importance: "core",
    skill: "understand",
    sources: [kf(2, "Sickness cover", "18–19")],
    confusedWith: ["motor-comp"],
    mcq: {
      stem: "A personal accident and sickness policy has a seven-day time franchise on sickness. The insured is ill for 10 days. What is normally paid?",
      options: [
        "Nothing, because the first week is always excluded",
        "Three days’ benefit only",
        "Benefit for the entire ten days",
        "A capital sum instead of weekly benefit",
      ],
      correct: 2,
      whyWrong: [
        "That describes an excess/waiting period that is deducted, not a franchise that opens the whole period.",
        "The franchise is not a simple three-day remainder.",
        "Correct: once the seven-day threshold is passed, the whole period is covered.",
        "Sickness TTD is weekly, not a capital sum.",
      ],
    },
  },
  {
    id: "h-ttd-weeks",
    chapter: 2,
    section: "Temporary total disablement",
    conceptId: "health-pas-benefits",
    title: "TTD up to 104 weeks",
    kind: "limit",
    claim:
      "Temporary total disablement from usual occupation pays a weekly benefit (example [[£200]] per week) for a maximum of [[104 weeks]] (some insurers 52 weeks at a higher limit). Accident weekly benefit may also run up to 104 weeks. TPD (temporary partial) is accident-only, often about [[40%]] of TTD, example £100/week.",
    importance: "supporting",
    skill: "know",
    sources: [kf(2, "Temporary total disablement", "20–21")],
  },
  {
    id: "h-geo-age",
    chapter: 2,
    section: "Limitations",
    conceptId: "health-pas-limits",
    title: "PAS geography and age",
    kind: "rule",
    claim:
      "Accident cover is usually [[worldwide]] (sometimes no benefit if residing outside the UK more than 180 consecutive days). Sickness is generally [[UK, Europe, USA, Canada, Australia and New Zealand]]. Typical inception ages: accident [[16–70]], sickness [[16–60]]. Family policies may include children (often 6 months–16, sometimes to 23 in full-time education) at lower benefits.",
    importance: "supporting",
    skill: "know",
    sources: [kf(2, "Geographical limits / Age limits", "21–22")],
  },
  {
    id: "h-pas-excl",
    chapter: 2,
    section: "Exclusions",
    conceptId: "health-pas",
    title: "Typical PAS exclusions",
    kind: "exclusion",
    claim:
      "Typical exclusions include alcohol/drugs (unless medically supervised), [[self-inflicted]] injury, pre-existing physical defects before an accident, specified sports (aviation other than as passenger, motor cycling, polo, racing, winter sports, roped mountaineering) unless extra premium, childbirth/pregnancy/VD/AIDS, war, and sickness in the first 21 days.",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Exclusions", "22")],
  },
  {
    id: "h-pmi-choice",
    chapter: 2,
    section: "Medical expenses insurance",
    conceptId: "health-medexp",
    title: "Private medical / health care purpose",
    kind: "definition",
    claim:
      "Medical expenses (health care) insurance funds [[private treatment outside the NHS]], giving choice of specialist, hospital and timing. It is often arranged as an employer [[group]] scheme.",
    importance: "supporting",
    skill: "know",
    sources: [kf(2, "Medical expenses insurance", "22–23")],
  },

  {
    id: "p-homogeneity",
    chapter: 3,
    section: "Introduction",
    conceptId: "package-idea",
    title: "Homogeneity of risks",
    kind: "definition",
    claim:
      "Packages are used where there is [[homogeneity of risks]] — many risks share similar characteristics — so claims costs are more predictable, wordings can be standardised, and a [[single premium]] covers all included classes, with savings passed to qualifying insureds.",
    importance: "core",
    skill: "understand",
    sources: [kf(3, "Introduction", "25")],
  },
  {
    id: "p-buildings-def",
    chapter: 3,
    section: "Building insurance",
    conceptId: "hh-buildings",
    title: "What ‘buildings’ includes",
    kind: "definition",
    claim:
      "Household buildings means the main dwelling plus [[garages, sheds, greenhouses and other outbuildings]], swimming pools, tennis courts, walls, gates, fences and paths. The buildings sum insured should be the [[rebuilding cost when rebuilding is complete]].",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Building insurance", "26")],
  },
  {
    id: "p-unoccupied-30",
    chapter: 3,
    section: "Riot, civil commotion",
    conceptId: "hh-unoccupied",
    title: "Unoccupied / unfurnished 30 or 60 days",
    kind: "exclusion",
    claim:
      "Riot/malicious damage, escape of water/oil, theft and glass/sanitary breakage commonly exclude loss while [[unfurnished or unoccupied for more than 30 or 60 days]] in the period. Malicious damage usually needs an excess and [[police notified]].",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Riot / Theft / Escape of water", "27–29")],
  },
  {
    id: "p-storm-excl",
    chapter: 3,
    section: "Storm or flood",
    conceptId: "hh-storm",
    title: "Storm or flood exclusions",
    kind: "exclusion",
    claim:
      "Storm or flood specifically excludes damage by [[frost, subsidence, ground heave or landslip]] and damage to [[gates, fences or hedges]]. An excess always applies. Falling trees also exclude walls/gates/fences/hedges.",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Storm or flood", "27")],
    confusedWith: ["hh-buildings"],
  },
  {
    id: "p-theft-act",
    chapter: 3,
    section: "Theft or attempted theft",
    conceptId: "hh-theft",
    title: "Household theft follows the Theft Act",
    kind: "definition",
    claim:
      "There is [[no special restriction]] on ‘theft’ in household wordings: insurers cover theft as in the [[Theft Act 1968]] — dishonest appropriation of property belonging to another with intent to permanently deprive.",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Theft or attempted theft", "29")],
    confusedWith: ["prop-theft"],
  },
  {
    id: "p-aerials",
    chapter: 3,
    section: "Breakage or collapse of television or radio",
    conceptId: "hh-buildings",
    title: "Aerial collapse vs the aerial itself",
    kind: "distinction",
    claim:
      "Buildings cover damage to the building from collapse of TV/radio aerials, [[not damage to the aerial itself]] (that is normally [[contents]]).",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Breakage or collapse of television or radio", "30")],
  },
  {
    id: "p-fees-rent",
    chapter: 3,
    section: "Legal fees, architects’ and surveyors’ fees",
    conceptId: "hh-buildings",
    title: "Fees, debris, loss of rent",
    kind: "cover",
    claim:
      "Reasonable legal/architects’/surveyors’ fees for reinstatement, demolition, shoring and debris removal are covered; [[costs of preparing the claim]] are excluded. Loss of rent can include ground rent and alternative accommodation as worded.",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Legal fees / Loss of rent", "29–30")],
  },
  {
    id: "p-possessions",
    chapter: 3,
    section: "Personal possessions",
    conceptId: "hh-possessions",
    title: "Personal possessions all risks",
    kind: "cover",
    claim:
      "Personal possessions extensions cover specified or unspecified items [[away from the home]] on an all-risks basis, subject to single-article limits and often a requirement to specify high-value items.",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Personal possessions", "36–37")],
    prerequisites: ["hh-contents"],
  },
  {
    id: "p-travel",
    chapter: 3,
    section: "Travel insurance",
    conceptId: "hh-travel",
    title: "Travel as a package",
    kind: "cover",
    claim:
      "Travel insurance is commonly a package of medical expenses, personal accident (fixed benefits), personal possessions, personal liability and cancellation/curtailment. PA pays a [[fixed benefit]]; medical expenses reimburse costs.",
    importance: "core",
    skill: "know",
    sources: [eg("14", "1.1"), kf(3, "Travel insurance", "40")],
  },
  {
    id: "p-shop-office",
    chapter: 3,
    section: "Commercial packages",
    conceptId: "package-commercial",
    title: "Shop, office, tradesman, hotel packages",
    kind: "cover",
    claim:
      "Commercial packages exist for shopkeepers, offices, tradesmen and hotels, bundling property, money, glass, liability and often BI where the risk class is homogeneous enough to standardise.",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Commercial packages", "41–46")],
  },
  {
    id: "p-pets-impact",
    chapter: 3,
    section: "Impact/collision",
    conceptId: "hh-buildings",
    title: "Impact excesses and pets",
    kind: "exclusion",
    claim:
      "Impact cover includes aircraft, dropped articles, road vehicles or animals. There may be an excess for the [[insured’s or family’s vehicles or animals]]. Damage caused by [[pets]] is usually excluded.",
    importance: "detail",
    skill: "know",
    sources: [kf(3, "Impact/collision", "28")],
  },

  {
    id: "pr-special-perils",
    chapter: 4,
    section: "Fire and special perils insurance",
    conceptId: "prop-fire",
    title: "Fire plus special perils",
    kind: "cover",
    claim:
      "A standard fire policy is the base unless packaged; [[special perils]] (and sometimes all risks) are added. The proposer sets the [[sum insured]]; the insurer rates.",
    importance: "core",
    skill: "know",
    sources: [kf(4, "Fire and special perils insurance", "47")],
  },
  {
    id: "pr-theft-force",
    chapter: 4,
    section: "Theft insurance",
    conceptId: "prop-theft",
    title: "Forcible and violent entry",
    kind: "definition",
    claim:
      "Commercial theft wordings typically require [[forcible and violent]] entry or exit so people cannot hide on the premises and walk out. This is stricter than household theft under the Theft Act.",
    importance: "core",
    skill: "understand",
    sources: [kf(4, "Theft insurance", "54–55")],
    confusedWith: ["hh-theft"],
    mcq: {
      stem: "Why do commercial theft policies usually require forcible and violent entry or exit?",
      options: [
        "Because the Theft Act 1968 always requires force",
        "To stop persons hiding on the premises and later walking out with goods",
        "Because hold-up is otherwise uncovered",
        "Because average cannot apply without force",
      ],
      correct: 1,
      whyWrong: [
        "The Theft Act does not always require force; household cover follows that Act without the force condition.",
        "Correct: the wording exists to eliminate hide-and-walk-out theft.",
        "Hold-up is a separate assault-accompanied theft definition.",
        "Average/underinsurance is a different mechanism.",
      ],
    },
  },
  {
    id: "pr-holdup",
    chapter: 4,
    section: "Theft insurance",
    conceptId: "prop-theft",
    title: "Hold-up",
    kind: "definition",
    claim:
      "[[Hold-up]] is theft accompanied by [[assault]]. First-loss sums insured are common because a total loss of all stock by theft is unlikely.",
    importance: "supporting",
    skill: "know",
    sources: [kf(4, "Theft insurance", "55–58")],
  },
  {
    id: "pr-money-limits",
    chapter: 4,
    section: "Limits of liability",
    conceptId: "prop-money",
    title: "Money out of a safe",
    kind: "limit",
    claim:
      "Money limits vary by situation. An example in the key facts is [[£500]] for money left [[out of a safe]] on the business premises. Credit cards are not in the standard money trio (cash, cheques, postage stamps).",
    importance: "core",
    skill: "know",
    sources: [kf(4, "Limits of liability", "62"), eg("20", "1.1")],
  },
  {
    id: "pr-glass-fire",
    chapter: 4,
    section: "Glass insurance",
    conceptId: "prop-glass",
    title: "Glass excludes fire and lightning",
    kind: "exclusion",
    claim:
      "Glass covers destruction or damage to [[fixed glass]]. It is standard to exclude damage by [[fire and lightning]], leaving those to the fire policy.",
    importance: "supporting",
    skill: "know",
    sources: [kf(4, "Glass insurance", "58–59")],
  },
  {
    id: "pr-average",
    chapter: 4,
    section: "Underinsurance",
    conceptId: "prop-theft",
    title: "Average on theft",
    kind: "rule",
    claim:
      "Theft policies, like many other property classes, commonly apply [[average]] if the sum insured is inadequate.",
    importance: "supporting",
    skill: "understand",
    sources: [kf(4, "Underinsurance", "57")],
  },

  {
    id: "pe-group-legal",
    chapter: 5,
    section: "Group legal benefit policies",
    conceptId: "pec-legal-group",
    title: "Group legal benefit sections",
    kind: "cover",
    claim:
      "Group legal benefit (employees and immediate family) offers choosable sections: [[employment]], [[personal]], [[motor]] (defence not covered by ordinary motor), and [[conveyancing]] (legal costs of buying/selling a house). Limits are per claim, not an overall period limit.",
    importance: "core",
    skill: "know",
    sources: [kf(5, "Group legal benefit policies", "63–64")],
    prerequisites: ["pec-legal"],
  },
  {
    id: "pe-comm-legal",
    chapter: 5,
    section: "Commercial legal protection policies",
    conceptId: "pec-legal",
    title: "Commercial legal sections",
    kind: "cover",
    claim:
      "Commercial legal protection sections include employment (unfair dismissal/discrimination plus awards), criminal prosecution defence (often HSWA — costs not [[fines]]), property disputes, motor (ULR etc.), and patents/IP. It does [[not]] cover public liability disputes.",
    importance: "core",
    skill: "know",
    sources: [kf(5, "Commercial legal protection policies", "64–66"), eg("23", "1.1")],
  },
  {
    id: "pe-icw",
    chapter: 5,
    section: "Extra costs",
    conceptId: "pec-bi",
    title: "Increased cost of working",
    kind: "cover",
    claim:
      "BI recognises extra expenses to keep the business going after insured damage ([[increased cost of working]]) as well as loss of [[turnover]]/gross profit, within the chosen maximum indemnity period.",
    importance: "core",
    skill: "understand",
    sources: [kf(5, "Extra costs / Turnover", "68–69")],
  },
  {
    id: "pe-declaration",
    chapter: 5,
    section: "Basis of fixing sums insured",
    conceptId: "pec-bi-sum",
    title: "Declaration-linked BI",
    kind: "procedure",
    claim:
      "BI sums insured can be a projected figure or [[declaration-linked]], which reduces the need to project far ahead and adjusts with declarations of actual turnover/gross profit.",
    importance: "supporting",
    skill: "know",
    sources: [kf(5, "Basis of fixing sums insured", "67–69")],
    prerequisites: ["pec-bi"],
  },

  {
    id: "l-el-trace",
    chapter: 6,
    section: "Employers’ liability insurance",
    conceptId: "el-compulsory",
    title: "EL tracing and certificates",
    kind: "procedure",
    claim:
      "Long-tail industrial disease claims led to an EL tracing service (1999, replaced 2011). From April 2012 the FCA requires participation so EL policies can be found online. Employers must provide the [[EL certificate]] to employees; each employer has a unique [[ERN]]. The 2008 amendment regulations (from 1 October 2008) changed display rules.",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Employers’ liability insurance", "73–76")],
  },
  {
    id: "l-el-occurrence",
    chapter: 6,
    section: "Period of insurance",
    conceptId: "el-cover",
    title: "EL is typically occurrence-based",
    kind: "distinction",
    claim:
      "EL generally responds to injury or disease [[caused during the period of insurance]] (occurrence), whereas D&O and PI are typically [['claims made']].",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Period of insurance", "78"), kf(6, "Directors’ and officers’ D&O", "86")],
    confusedWith: ["do-cover", "pi-cover"],
  },
  {
    id: "l-pl-conseq",
    chapter: 6,
    section: "Consequential loss",
    conceptId: "pl-cover",
    title: "PL consequential vs pure financial loss",
    kind: "distinction",
    claim:
      "Public liability covers physical injury and damage and [[consequential loss flowing from that damage]] (e.g. hire of a replacement car). Pure [[financial loss without]] material damage is more limited and not the core PL grant.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Consequential loss / Financial loss", "81–82")],
  },
  {
    id: "l-pl-limit",
    chapter: 6,
    section: "Limit of indemnity",
    conceptId: "pl-cover",
    title: "PL limits of indemnity",
    kind: "limit",
    claim:
      "PL limits are often [[£2 million]], with figures up to [[£10 million]] not uncommon, as a maximum following an occurrence as worded.",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Limit of indemnity", "82")],
  },
  {
    id: "l-claims-made",
    chapter: 6,
    section: "Directors’ and officers’ D&O",
    conceptId: "do-cover",
    title: "Claims-made trigger",
    kind: "definition",
    claim:
      "[['Claims made']] means the policy in force when the [[claim is made]] (not necessarily when the wrongful act occurred) is the one that responds, subject to retroactive dates and discovery extensions.",
    importance: "core",
    skill: "understand",
    sources: [kf(6, "Standard policy cover", "86–87")],
    confusedWith: ["el-cover"],
  },
  {
    id: "l-pension-trustee",
    chapter: 6,
    section: "Pension fund trustees",
    conceptId: "trustee-cover",
    title: "Pension fund trustees",
    kind: "cover",
    claim:
      "The Pensions Act 1995 and later rules impose duties on pension trustees. Trustee insurance covers internal [[wrongful acts]] in that role, limited by how ‘wrongful act’ is defined.",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Pension fund trustees", "90–91")],
  },
  {
    id: "l-ew-approved",
    chapter: 6,
    section: "Extended warranties",
    conceptId: "extended-warranty",
    title: "Approved repairers and sum insured",
    kind: "procedure",
    claim:
      "Extended warranty often requires repairs by [[approved agents]]. A typical sum insured example is [[£2,500]] per period for free repair or replacement after the maker’s guarantee.",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Extended warranties", "94")],
  },
];
