import type { AuthoredFact } from "../engine/types";

export const kf = (chapter: 1 | 2 | 3 | 4 | 5 | 6, section: string, page: string) => ({
  kind: "key-facts" as const,
  chapter,
  section,
  page,
  locator: `IF2 2026 Key Facts ch.${chapter} p.${page} — ${section}`,
});

export const st = (section: string, page: string) => ({
  kind: "study-text" as const,
  chapter: 1 as const,
  section,
  page,
  locator: `IF2 2026 Study Text ch.1 p.${page} — ${section}`,
});

export const sy = (outcome: string, note: string) => ({
  kind: "syllabus" as const,
  section: outcome,
  locator: `IF2 2026 syllabus ${outcome}`,
  note,
});

export const eg = (q: string, lo: string) => ({
  kind: "exam-guide" as const,
  section: lo,
  locator: `IF2 2026 Examination Guide specimen Q${q} (LO ${lo})`,
});

export const FACTS: AuthoredFact[] = [
  // ——— Chapter 1 Motor ———
  {
    id: "m-compulsory",
    chapter: 1,
    section: "Private motor insurance",
    conceptId: "motor-compulsory",
    title: "Compulsory motor insurance",
    kind: "rule",
    claim:
      "It is [[illegal to drive, or be in charge of, a vehicle on a public road]] unless a policy covers legal liability for injury to others and damage to their property.",
    extra:
      "Private motor insurance is the most significant compulsory insurance in the UK in terms of the number of people affected.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Private motor insurance", "5"), st("Introduction / Private motor", "1/2")],
    prediction: "Why is motor insurance treated as compulsory in the UK?",
    teachBackCue: "In one sentence, when is it illegal to be in charge of a vehicle without insurance?",
    mcq: {
      stem: "A motor vehicle must be insured unless",
      options: [
        "it is being kept in a garage and not driven on public roads",
        "it is kept on a private driveway and is not driven on public roads",
        "it is only driven on private roads and is not driven on public roads",
        "a Statutory Off Road Notification declaration is made to the DVLA",
      ],
      correct: 3,
      whyWrong: [
        "Keeping a vehicle in a garage does not by itself replace the need for insurance or a SORN.",
        "A private driveway is not the SORN route described in the specimen item.",
        "Use only on private roads is not the stated exception in the specimen item.",
        "Correct: a SORN declaration to the DVLA is the route in the specimen question.",
      ],
    },
  },
  {
    id: "m-sorn-exam",
    chapter: 1,
    section: "Private motor insurance",
    conceptId: "motor-compulsory",
    title: "SORN as the stated exception (exam guide)",
    kind: "rule",
    claim:
      "In the CII specimen paper, a motor vehicle must be insured unless [[a Statutory Off Road Notification (SORN) is made to the DVLA]].",
    importance: "core",
    skill: "know",
    sources: [eg("6", "1.1"), sy("1.1", "Motor products")],
    mcq: {
      stem: "A motor vehicle must be insured unless",
      options: [
        "it is being kept in a garage and not driven on public roads",
        "it is kept on a private driveway and is not driven on public roads",
        "it is only driven on private roads and is not driven on public roads",
        "a Statutory Off Road Notification declaration is made to the Driver and Vehicle Licensing Agency (DVLA)",
      ],
      correct: 3,
      whyWrong: [
        "Not the specimen exception.",
        "Not the specimen exception.",
        "Not the specimen exception.",
        "This is the specimen key.",
      ],
    },
  },
  {
    id: "m-four-levels",
    chapter: 1,
    section: "Standard policy cover",
    conceptId: "motor-cover-levels",
    title: "Four levels of private motor cover",
    kind: "cover",
    claim:
      "The four levels of private motor cover are [[Road Traffic Act only (RTA only)]], [[third party only (TPO)]], [[third party, fire and theft (TPFT)]] and [[comprehensive]].",
    extra:
      "Most insurers issue one standard form with numbered sections; the schedule identifies which sections apply. For practical purposes the lowest cover commonly offered is third party only, because RTA and TPO are now only marginally different.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Standard policy cover", "5"), st("A1 Standard policy cover", "1/2")],
    confusedWith: ["motor-rta", "motor-tpo", "motor-tpft", "motor-comp"],
    prediction: "Name the four levels of private motor cover from minimum to widest.",
  },
  {
    id: "m-rta-scope",
    chapter: 1,
    section: "Road Traffic Act only",
    conceptId: "motor-rta",
    title: "RTA only: where it applies",
    kind: "rule",
    claim:
      "RTA only is the [[minimum cover required to comply with the Road Traffic Act 1988]] (as amended) and relates to use of a motor vehicle [[on a road or any public place]].",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Road Traffic Act only", "5"), st("A1A Road Traffic Act only", "1/2–1/3")],
    prerequisites: ["motor-cover-levels"],
    confusedWith: ["motor-tpo"],
  },
  {
    id: "m-rta-bi",
    chapter: 1,
    section: "Road Traffic Act only",
    conceptId: "motor-rta",
    title: "RTA only: injury indemnity",
    kind: "limit",
    claim:
      "RTA only indemnifies for bodily injury or death caused to third parties, including passengers, [[unlimited in amount]].",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Road Traffic Act only", "5"), st("A1A", "1/3")],
  },
  {
    id: "m-rta-tppd",
    chapter: 1,
    section: "Road Traffic Act only",
    conceptId: "motor-rta",
    title: "RTA only: property damage limit",
    kind: "limit",
    claim:
      "RTA only indemnifies for loss of or damage to third party property limited to [[£1.2 million]].",
    extra:
      "The study text records that the European Commission increased the EU minimum to €1.2 million on 1 January 2017, and UK legislation increased the RTA limit to £1.2 million from 31 December 2016.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Road Traffic Act only", "5"), st("A1A", "1/2–1/3")],
    confusedWith: ["motor-tpo", "motor-commercial-tppd"],
  },
  {
    id: "m-rta-costs-emt",
    chapter: 1,
    section: "Road Traffic Act only",
    conceptId: "motor-rta",
    title: "RTA only: costs and emergency treatment",
    kind: "cover",
    claim:
      "RTA only also indemnifies [[claimants’ costs and claim-handling expenses]] and covers [[emergency medical treatment and hospital charges]] specified in the RTA, which the policy must pay when demanded.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Road Traffic Act only", "5–6"), st("A1A", "1/3")],
  },
  {
    id: "m-rta-eu",
    chapter: 1,
    section: "Road Traffic Act only",
    conceptId: "motor-rta",
    title: "Third EU Motor Insurance Directive extras",
    kind: "rule",
    claim:
      "To comply with the Third EU Motor Insurance Directive, all policies must provide [[the greater of the visited EU country’s minimum cover and the home-country (UK RTA) minimum]], and cover [[liability to employees travelling as passengers in the course of employment, but not the driver]] (the employer’s liability to the driver falls under employers’ liability).",
    importance: "supporting",
    skill: "understand",
    sources: [kf(1, "Road Traffic Act only", "6"), st("A1A", "1/3")],
    confusedWith: ["el-legal-liability"],
  },
  {
    id: "m-tpo-extras",
    chapter: 1,
    section: "Third party only (TPO)",
    conceptId: "motor-tpo",
    title: "What TPO adds to RTA",
    kind: "cover",
    claim:
      "TPO usually adds cover [[off road / not in a public place but within territorial limits]], a [[£20 million]] third party property damage limit for private cars, driving-other-cars indemnity (not all insurers), indemnity to permitted drivers/users unless named-driver restricted, indemnity to passengers/employers/partners, defence costs, and limited motoring-prosecution legal representation.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Third party only (TPO)", "6"), st("A1B Third party only", "1/3")],
    prerequisites: ["motor-rta"],
    confusedWith: ["motor-rta", "motor-tpft"],
    teachBackCue: "Name three things TPO usually adds that RTA only does not.",
  },
  {
    id: "m-tpo-exclusions",
    chapter: 1,
    section: "Third party only (TPO)",
    conceptId: "motor-tpo",
    title: "TPO third-party exclusions",
    kind: "exclusion",
    claim:
      "Specific third party exclusions include [[damage to property (including the vehicle) owned, held in trust, or in the custody/control of the person claiming indemnity]] and [[liability covered by any other insurance]] (especially driving another vehicle that has a more specific policy).",
    importance: "core",
    skill: "know",
    sources: [st("A1B", "1/3")],
  },
  {
    id: "m-tpft",
    chapter: 1,
    section: "Third party, fire and theft (TPFT)",
    conceptId: "motor-tpft",
    title: "TPFT own-vehicle cover",
    kind: "cover",
    claim:
      "TPFT adds, on top of TPO, repair cost or compensation if the insured’s vehicle is [[damaged by fire, lightning or explosion]], [[damaged during attempted theft or while stolen]] (some policies include taking without consent), or [[stolen and not recovered]].",
    extra: "Fire and theft cover specifically excludes loss of use.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Third party, fire and theft (TPFT)", "7"), st("A1C", "1/4")],
    confusedWith: ["motor-comp"],
  },
  {
    id: "m-comp",
    chapter: 1,
    section: "Comprehensive",
    conceptId: "motor-comp",
    title: "Comprehensive as ‘all risks’ of own damage",
    kind: "cover",
    claim:
      "Comprehensive is the widest usual private motor cover: TPFT plus [[other accidental and malicious damage]] to the insured’s car, on an [['all risks' basis]] subject to specific exclusions.",
    extra:
      "Typical extras include personal accident cover, medical expenses, and personal belongings and clothing. Driving-other-cars under a comprehensive policy is still only third party — no cover for damage to the other vehicle being driven.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Comprehensive", "7–8"), st("A1D", "1/4–1/5")],
    confusedWith: ["motor-tpft"],
  },
  {
    id: "m-comp-excl",
    chapter: 1,
    section: "Comprehensive",
    conceptId: "motor-comp",
    title: "Comprehensive own-damage exclusions",
    kind: "exclusion",
    claim:
      "Comprehensive typically excludes [[accessories/spares not on the vehicle or in the insured’s garage]], [[wear and tear and depreciation]], [[loss of use]] (unless a limited extra is granted), [[mechanical/electrical failure or breakdown]] (but collision damage caused by sudden brake failure is covered), and [[tyre damage from punctures or bursts]].",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Comprehensive", "7"), st("A1D", "1/4")],
  },
  {
    id: "m-young-excess",
    chapter: 1,
    section: "Comprehensive",
    conceptId: "motor-comp",
    title: "Young or inexperienced drivers excess",
    kind: "rule",
    claim:
      "A [['young or inexperienced drivers' excess]] applies on top of any policy excess. ‘Inexperienced’ means holding a [[provisional licence]] or [[not having held a full licence for at least a year]]. Some insurers exclude driving-other-cars entirely for drivers under 25. An excess is [[the first amount of each and every claim the insured must bear]].",
    importance: "supporting",
    skill: "know",
    sources: [st("A1D", "1/4")],
  },
  {
    id: "m-ncd",
    chapter: 1,
    section: "No claims discount (NCD)",
    conceptId: "motor-ncd",
    title: "No claims discount",
    kind: "procedure",
    claim:
      "NCD and ‘no claims bonus’ are [[interchangeable]]. Illustrative discounts are about [[12% after one claim-free year]] up to [[50%+ after five or more]]. Insurers generally [[drop back two years]] after a claim. Protection (modest defined claims) or a ‘guaranteed’ discount after five years may be bought; this does [[not]] guarantee the underlying premium.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "No claims discount (NCD)", "8"), st("A1E", "1/5")],
  },
  {
    id: "m-glass-ncd",
    chapter: 1,
    section: "Breakage of glass",
    conceptId: "motor-ncd",
    title: "Windscreen claims and NCD",
    kind: "rule",
    claim:
      "Glass breakage is standard on comprehensive policies (optional extra on non-comprehensive). A claim [[under this section alone does not affect NCD]].",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Breakage of glass", "8–9"), st("A2A", "1/5")],
  },
  {
    id: "m-uninsured-promise",
    chapter: 1,
    section: "Uninsured driver promise",
    conceptId: "motor-uninsured-promise",
    title: "Uninsured driver promise",
    kind: "cover",
    claim:
      "On some comprehensive policies, if the other vehicle is uninsured, the extension usually protects [[NCD and the policy excess]] provided [[full details of the third party vehicle]] are given. It does [[not]] apply to [['hit and run' / untraced]] accidents.",
    importance: "supporting",
    skill: "know",
    sources: [kf(1, "Uninsured driver promise", "8"), st("A1F", "1/5")],
  },
  {
    id: "m-foreign",
    chapter: 1,
    section: "Foreign use",
    conceptId: "motor-foreign",
    title: "Foreign use and green cards",
    kind: "rule",
    claim:
      "UK policies must extend to [[the greater of visited-country minimum and home minimum]]. Matching full UK cover abroad usually needs [[notification and a continental-use extension]] (sometimes free for up to 30 days). A green card is an international certificate; from [[2 August 2021]] the UK participates in the Green Card Free Circulation Area, removing the need for green cards in listed European countries (many insurers still issued them until 2 September 2021 following MIB recommendation).",
    importance: "supporting",
    skill: "know",
    sources: [kf(1, "Foreign use", "10"), st("A2F", "1/6")],
  },
  {
    id: "m-exclusions-rta-pay",
    chapter: 1,
    section: "Exclusions",
    conceptId: "motor-exclusions",
    title: "RTA claims despite policy exclusions",
    kind: "rule",
    claim:
      "The Road Traffic Acts require an insurer to [[pay an RTA claim even if the policy wording excludes it]], so innocent victims are compensated; the insurer may [[recover its outlay from the insured]].",
    extra:
      "General exclusions include unlicensed drivers, use outside the certificate, contractual liability, war, radioactive contamination/nuclear assembly, riot and civil commotion in Northern Ireland for own damage, sonic bangs, and pollution unless from a single identifiable event. Unroadworthy use and licence conditions also appear.",
    importance: "core",
    skill: "understand",
    sources: [st("A3 Exclusions", "1/8"), kf(1, "Exclusions", "14–15")],
  },
  {
    id: "m-use",
    chapter: 1,
    section: "Use of the insured vehicle",
    conceptId: "motor-use",
    title: "Use as described in the certificate",
    kind: "exclusion",
    claim:
      "Liability is excluded while the vehicle is used [[for a purpose outside the description of use in the certificate of motor insurance]]. Peer-to-peer renting is usually excluded from personal policies. Informal car sharing may stay valid [[if no profit is made from the passenger contribution]], but commuting/business versus SDP use can change coverage.",
    importance: "supporting",
    skill: "understand",
    sources: [st("A3A Use of the insured vehicle", "1/8")],
    scenario: {
      setup: "An insured gives a neighbour a lift to the same workplace and accepts a contribution that does not make a profit.",
      question: "Does the study text say a standard hire-and-reward exclusion necessarily voids the policy?",
      answer:
        "If no profit is made from the passenger contribution the policy should remain valid, but different work destinations or business-use issues can be more complex.",
    },
  },
  {
    id: "m-bike",
    chapter: 1,
    section: "Motorcycle insurance",
    conceptId: "motor-cycle",
    title: "Motorcycle vs private car comprehensive",
    kind: "distinction",
    claim:
      "‘Motorcycle’ includes [[any mechanically propelled cycle, including mopeds]]. Cover is [[specified motorcycle insurance]] for a particular machine. Differences versus private comprehensive: accessories/spares stolen [[only if the motorcycle is stolen at the same time]]; [[no personal accident benefits]] and [[no medical expenses beyond emergency treatment fees]] or personal effects.",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Motorcycle insurance", "15"), st("B Motorcycle insurance", "1/9")],
    confusedWith: ["motor-comp"],
    mcq: {
      stem: "Under a motorcycle policy, accessories are only covered if stolen",
      options: [
        "from a locked garage",
        "from the motorcycle",
        "using force and violence",
        "with the motorcycle",
      ],
      correct: 3,
      whyWrong: [
        "Garage theft of accessories alone is not the motorcycle rule.",
        "Accessories stolen from the bike while it remains are not covered under the accidental damage difference stated.",
        "Force and violence is a theft-policy idea, not this motorcycle accessories rule.",
        "Correct: stolen with the motorcycle.",
      ],
    },
  },
  {
    id: "m-bike-tpo-emt",
    chapter: 1,
    section: "Motorcycle insurance",
    conceptId: "motor-cycle",
    title: "TPO motorcycle includes emergency treatment",
    kind: "cover",
    claim:
      "Under a third party only motorcycle policy, [[emergency treatment fees]] form part of standard cover; clothing/personal effects, medical expenses and personal accident benefits do not.",
    importance: "core",
    skill: "know",
    sources: [st("Question 1.2 / B1", "1/9–1/10")],
  },
  {
    id: "m-comm-scope",
    chapter: 1,
    section: "Commercial motor insurance",
    conceptId: "motor-commercial",
    title: "What commercial motor covers — and does not",
    kind: "definition",
    claim:
      "Commercial motor concerns risks to the [[vehicles themselves]] while driven, parked, or carried by sea/air between UK parts. It does [[not]] cover goods carried; that is [[goods in transit]]. Main types: goods-carrying, passenger-carrying, agricultural/forestry, and special types (ambulances, cranes, fork-lifts).",
    importance: "core",
    skill: "know",
    sources: [kf(1, "Commercial motor insurance", "16"), st("C Commercial motor", "1/10")],
  },
  {
    id: "m-comm-tppd",
    chapter: 1,
    section: "Third party liability",
    conceptId: "motor-commercial-tppd",
    title: "Commercial third party property damage limits",
    kind: "limit",
    claim:
      "Death/bodily injury indemnity is [[unlimited]] for private and commercial motor. Private cars usually have [[£20 million]] TPPD; commercial is often about [[£5 million]], and general haulage may be as low as the [[£1.2 million]] compulsory minimum. Limits can be increased for extra premium.",
    extra:
      "The study text asks why a limit is needed: size, weight and cargo of some commercial vehicles could cause considerable damage. The specimen paper asks the minimum legal TPPD limit for commercial vehicles: £1,200,000.",
    importance: "core",
    skill: "know",
    sources: [st("C1A", "1/11"), kf(1, "Third party liability", "17"), eg("7", "1.1")],
    confusedWith: ["motor-rta", "motor-tpo"],
    mcq: {
      stem: "What is the minimum legal limit of indemnity in respect of third party property damage under a commercial vehicle insurance policy?",
      options: ["£100,000", "£250,000", "£500,000", "£1,200,000"],
      correct: 3,
      whyWrong: [
        "Too low — not the RTA/commercial minimum in the materials.",
        "Too low.",
        "Too low.",
        "Matches the £1.2 million RTA property damage minimum used for restricted commercial/haulage limits.",
      ],
    },
  },
  {
    id: "m-comm-omit",
    chapter: 1,
    section: "Private motor policies only",
    conceptId: "motor-commercial",
    title: "Covers omitted from commercial motor",
    kind: "distinction",
    claim:
      "Commercial comprehensive usually omits [[driving other vehicles]] (vehicle range too wide) and [['personal benefits']] — personal accident, medical expenses, personal belongings. Loading/unloading third party cover and trailer rules are commercial-specific additions. Spare parts/accessories are covered on the vehicle, [[not while detached]] (unlike private motor garage cover).",
    importance: "core",
    skill: "know",
    sources: [st("C1B–C1D", "1/11"), kf(1, "Loss of or damage / Optional", "18–19")],
    mcq: {
      stem: "What cover is omitted from a comprehensive commercial vehicle insurance policy which would be provided under a comprehensive private car insurance policy?",
      options: [
        "Foreign use",
        "Legal costs in defence of a claim",
        "Personal accident benefits",
        "Towing of a disabled vehicle",
      ],
      correct: 2,
      whyWrong: [
        "Foreign use is not the omitted personal-benefits class.",
        "Legal defence costs are part of commercial third party notes.",
        "Correct: personal accident benefits are a private-motor personal benefit omitted commercially.",
        "Towing/disabled vehicle notes exist in commercial trailer cover.",
      ],
    },
  },
  {
    id: "m-st-q11",
    chapter: 1,
    section: "Comprehensive",
    conceptId: "motor-comp",
    title: "Breakdown recovery is not standard comprehensive",
    kind: "cover",
    claim:
      "Standard comprehensive private motor includes accidental damage, driver’s PA benefit, recovery after an accident, and third party liability. [[Recovery after breakdown]] is an optional extra, not standard.",
    importance: "supporting",
    skill: "know",
    sources: [st("Question 1.1", "1/9"), st("A2J Breakdown cover", "1/7")],
  },

  // ——— Chapter 2 Health ———
  {
    id: "h-pas-nature",
    chapter: 2,
    section: "Personal accident and sickness",
    conceptId: "health-pas",
    title: "PA & sickness is a benefit contract",
    kind: "definition",
    claim:
      "Personal accident and sickness is a relatively simple policy. Occupation is the [[main rating factor]]. It is [[not a contract of indemnity]]; it pays [[stated benefits]]. Insurers still try to avoid over-insurance. It is sold standalone and as an add-on.",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Personal accident and sickness insurance", "17")],
    prediction: "Is personal accident insurance an indemnity policy? What is the main rating factor?",
  },
  {
    id: "h-death-12",
    chapter: 2,
    section: "Death",
    conceptId: "health-pas-benefits",
    title: "Death time limit",
    kind: "rule",
    claim:
      "Insurers often stipulate that death must occur within [[twelve months]] of the accident for a death claim.",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Death", "19"), eg("12", "1.1")],
    mcq: {
      stem: "In order for a death claim to be made under a personal accident insurance policy, death must usually occur within how many months of the accident?",
      options: ["12 months", "18 months", "24 months", "36 months"],
      correct: 0,
      whyWrong: [
        "Correct: twelve months is the usual stipulation in the key facts.",
        "Longer than the usual key-facts period.",
        "Used elsewhere (e.g. waiting to assess PTD), not the usual death window.",
        "Not the usual death window.",
      ],
    },
  },
  {
    id: "h-capital",
    chapter: 2,
    section: "Policy benefits",
    conceptId: "health-pas-benefits",
    title: "Capital vs weekly benefits",
    kind: "cover",
    claim:
      "[[Capital sums (lump sums)]] are paid for death and specified losses (sight/limbs). Temporary total/partial disablement pays [[weekly benefits]], often limited (e.g. 52 weeks). Permanent total disablement may wait [[12 or 24 months]] to be assessed. Permanent partial disablement is [[not standard]]. Travel PA pays a [[fixed benefit]] (specimen).",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Policy benefits", "19–21"), eg("14", "1.1")],
  },
  {
    id: "h-sickness-deferred",
    chapter: 2,
    section: "Sickness cover",
    conceptId: "health-pas",
    title: "Sickness waiting / deferred period",
    kind: "rule",
    claim:
      "Sickness cover generally excludes sickness contracted within an initial period, and weekly sickness claims typically [[do not pay the first days]] (key facts: if sickness continues beyond seven days the claim may then be paid), so the insurer covers new sickness arising after inception, not immediately preexisting onset.",
    importance: "supporting",
    skill: "understand",
    sources: [kf(2, "Sickness cover", "18–19")],
  },
  {
    id: "h-suicide",
    chapter: 2,
    section: "Exclusions",
    conceptId: "health-pas",
    title: "Failed suicide and PAS",
    kind: "exclusion",
    claim:
      "A failed suicide attempt causing temporary partial disablement [[does not normally attract benefit]] under personal accident and sickness insurance.",
    importance: "core",
    skill: "know",
    sources: [eg("18", "1.1"), kf(2, "Exclusions", "22")],
    mcq: {
      stem: "A failed suicide attempt results in temporary partial disablement. What benefit, if any, can normally be claimed under a personal accident and sickness insurance policy?",
      options: [
        "The cost of medical expenses",
        "A fixed weekly benefit until recovery",
        "A lump sum",
        "No benefit can be claimed",
      ],
      correct: 3,
      whyWrong: [
        "Medical expenses are not the usual PAS response to this excluded event.",
        "Weekly TPD is not paid for this excluded cause.",
        "Capital benefit is not paid for this excluded cause.",
        "Correct: no benefit is normally payable.",
      ],
    },
  },
  {
    id: "h-medexp",
    chapter: 2,
    section: "Medical expenses insurance",
    conceptId: "health-medexp",
    title: "Medical expenses / health care",
    kind: "cover",
    claim:
      "Medical expenses (health care) insurance pays specified treatment costs (hospital, specialist, extras). It generally does [[not]] pay [[long-term residential care]].",
    importance: "core",
    skill: "know",
    sources: [kf(2, "Medical expenses insurance", "22–24"), eg("11", "1.1")],
    mcq: {
      stem: "A medical expenses policy will generally NOT pay the cost of",
      options: [
        "ambulance fees",
        "anaesthetist’s fees",
        "long-term residential care",
        "surgical dressings",
      ],
      correct: 2,
      whyWrong: [
        "Ambulance fees are typical acute treatment costs.",
        "Anaesthetist’s fees are typical surgical costs.",
        "Correct: long-term residential care is outside general medical expenses cover.",
        "Dressings are typical treatment costs.",
      ],
    },
  },
  {
    id: "h-travel-pa",
    chapter: 2,
    section: "Policy benefits",
    conceptId: "health-pas-benefits",
    title: "Travel personal accident is a fixed benefit",
    kind: "cover",
    claim:
      "Under a travel policy, a [[fixed benefit]] is paid under the [[personal accident]] section, not medical expenses, personal liability or possessions.",
    importance: "supporting",
    skill: "know",
    sources: [eg("14", "1.1")],
    mcq: {
      stem: "Under which section of a travel insurance policy would a fixed benefit be paid in the event of a claim?",
      options: ["Medical expenses", "Personal accident", "Personal liability", "Personal possessions"],
      correct: 1,
      whyWrong: [
        "Medical expenses reimburse costs, they are not the fixed-benefit PA section.",
        "Correct.",
        "Liability is indemnity to third parties.",
        "Possessions are property, not a capital accident benefit.",
      ],
    },
  },

  // ——— Chapter 3 Package ———
  {
    id: "p-why",
    chapter: 3,
    section: "Introduction",
    conceptId: "package-idea",
    title: "Why package policies exist",
    kind: "definition",
    claim:
      "Insurers package covers where many insureds need the same combination; [[administration savings]] are passed on as [[reduced premium]] compared with buying each class separately.",
    importance: "core",
    skill: "understand",
    sources: [kf(3, "Introduction", "25")],
    prediction: "Why would an insurer sell household or shop covers as a package rather than separate policies?",
  },
  {
    id: "p-hh-settle",
    chapter: 3,
    section: "Household insurance",
    conceptId: "hh-settlement",
    title: "Indemnity vs new for old",
    kind: "distinction",
    claim:
      "Household settlement is generally [[indemnity (market value, allowing for wear and tear)]] or [[new for old (reinstatement without deduction for wear and tear)]]. Some insurers barely offer indemnity. Buildings sums insured are typically reinstatement of the structure.",
    importance: "core",
    skill: "understand",
    sources: [kf(3, "Household insurance", "25–26")],
    confusedWith: [],
  },
  {
    id: "p-buildings-perils",
    chapter: 3,
    section: "Building insurance",
    conceptId: "hh-buildings",
    title: "Core buildings perils",
    kind: "cover",
    claim:
      "Household buildings typically cover fire/lightning/explosion/earthquake; riot/civil commotion/strikes (wordings often exclude certain Northern Ireland risks); storm or flood (with specific exclusions); falling trees; escape of water; escape of oil; theft; impact; subsidence/heave/landslip; aerial collapse; accidental damage to drains/pipes/cables; glass and sanitary ware; plus fees and loss of rent as described.",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Building insurance", "26–32")],
  },
  {
    id: "p-subsidence-xs",
    chapter: 3,
    section: "Subsidence, ground heave or landslip",
    conceptId: "hh-buildings",
    title: "Subsidence excess",
    kind: "limit",
    claim:
      "Subsidence cover under household buildings normally carries a substantial excess of, for example, [[£1,000]] or more.",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Subsidence, ground heave or landslip", "30"), eg("15", "1.1")],
    mcq: {
      stem: "What is the normal excess applicable to subsidence cover under a household buildings insurance policy?",
      options: ["£250", "£500", "£750", "£1,000"],
      correct: 3,
      whyWrong: [
        "Typical day-to-day excess territory, not the usual subsidence figure in the materials.",
        "Still below the usual subsidence example.",
        "Still below the usual subsidence example.",
        "Correct: £1,000 (or more) is the stated example.",
      ],
    },
  },
  {
    id: "p-coastal",
    chapter: 3,
    section: "Storm or flood",
    conceptId: "hh-buildings",
    title: "Coastal erosion not covered",
    kind: "exclusion",
    claim:
      "A standard household policy for a house near the sea would not normally cover [[coastal erosion]]. Storm, flood and heave may still be relevant perils depending on wording; the specimen excludes coastal erosion specifically.",
    importance: "core",
    skill: "know",
    sources: [eg("16", "1.1"), kf(3, "Storm or flood / Subsidence", "28–30")],
    mcq: {
      stem: "A standard household insurance policy for a house near the sea would NOT normally cover damage to the house arising from",
      options: ["coastal erosion", "ground heave", "a hurricane force wind", "tidal flooding"],
      correct: 0,
      whyWrong: [
        "Correct: coastal erosion is outside normal household cover.",
        "Heave is a listed buildings peril (with a large excess).",
        "Storm/wind is a standard peril.",
        "Flood/tidal flooding is in the storm or flood family unless specifically excluded.",
      ],
    },
  },
  {
    id: "p-theft-unoccupied",
    chapter: 3,
    section: "Theft or attempted theft",
    conceptId: "hh-buildings",
    title: "Unoccupied theft exclusion (household)",
    kind: "exclusion",
    claim:
      "Theft cover is usually excluded while premises are left [[unoccupied / insufficiently furnished]] for a defined period (wordings vary).",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Theft or attempted theft", "29")],
  },
  {
    id: "p-ad-ext",
    chapter: 3,
    section: "Accidental damage extension",
    conceptId: "hh-buildings",
    title: "Accidental damage is usually an extra",
    kind: "cover",
    claim:
      "Many insurers offer an [[accidental damage extension]] to buildings (e.g. drilling through a pipe). It is not the same as the named-perils core.",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Accidental damage extension", "32")],
  },
  {
    id: "p-contents",
    chapter: 3,
    section: "Contents insurance",
    conceptId: "hh-contents",
    title: "Contents: same perils, extra limits",
    kind: "cover",
    claim:
      "Contents perils broadly [[mirror buildings]]. There are [[single-article limits]] and high-value item rules. Automatic extras appear in many wordings; optional extras include personal possessions, money and credit cards, bicycles, freezer contents, caravans.",
    importance: "core",
    skill: "know",
    sources: [kf(3, "Contents insurance", "32–38")],
  },
  {
    id: "p-allrisks-away",
    chapter: 3,
    section: "Personal possessions",
    conceptId: "hh-all-risks",
    title: "All risks usually means away from the risk address",
    kind: "definition",
    claim:
      "When a commercial (or household possessions) policy includes an all risks section, this usually means cover [[away from the risk address]] — not ‘no excess’, not electrical breakdown, not agreed value as the meaning of the phrase in the specimen item.",
    importance: "core",
    skill: "know",
    sources: [eg("19", "1.1"), kf(3, "Personal possessions", "36–37")],
    confusedWith: ["prop-fire"],
    mcq: {
      stem: "When a commercial insurance policy includes an all risks section, this usually means that cover is provided",
      options: [
        "away from the risk address",
        "including electrical breakdown",
        "on an agreed value basis",
        "with no excess",
      ],
      correct: 0,
      whyWrong: [
        "Correct for the specimen meaning of an all risks section.",
        "Breakdown is typically excluded or separately engineered.",
        "Agreed value is a settlement basis, not the meaning of all risks here.",
        "Excesses still apply.",
      ],
    },
  },
  {
    id: "p-liability-hh",
    chapter: 3,
    section: "Legal liability: building and contents",
    conceptId: "hh-liability",
    title: "Household liability sections",
    kind: "cover",
    claim:
      "Buildings liability includes occupiers’/owners’ liability and Defective Premises Act (and NI Order 1975) for former property. Contents includes personal liability for accidental injury (as defined) and property damage.",
    importance: "supporting",
    skill: "know",
    sources: [kf(3, "Legal liability: building and contents", "35–36")],
  },
  {
    id: "p-riot-property",
    chapter: 3,
    section: "Riot, civil commotion",
    conceptId: "hh-buildings",
    title: "Riot damage class",
    kind: "cover",
    claim:
      "In certain areas of the UK, riot damage is usually covered under [[property]] insurance (not money, public liability or travel as the primary class).",
    importance: "supporting",
    skill: "know",
    sources: [eg("13", "1.1"), kf(3, "Riot, civil commotion, strikes", "27")],
    mcq: {
      stem: "In certain areas of the UK, riot damage is usually covered under which type of insurance policy?",
      options: ["Money", "Property", "Public liability", "Travel"],
      correct: 1,
      whyWrong: [
        "Money is a pecuniary/property subclass for cash etc., not the riot buildings/contents class.",
        "Correct.",
        "Public liability is third party injury/property, not the insured’s riot damage.",
        "Travel is not the usual UK riot vehicle.",
      ],
    },
  },
  {
    id: "p-shop-glass",
    chapter: 3,
    section: "Commercial packages",
    conceptId: "package-commercial",
    title: "Shop plate glass includes the frame in the specimen",
    kind: "example",
    claim:
      "If a shop policy includes plate glass and an employee breaks the window and wooden frame, the specimen key is that [[both the window and the wooden frame]] are covered.",
    importance: "supporting",
    skill: "apply",
    sources: [eg("17", "1.1")],
    mcq: {
      stem: "A shop owner has a commercial insurance policy which includes cover for plate glass. An employee accidentally breaks the shop window and wooden frame. Which of the damaged items, if either, is covered?",
      options: ["Neither of them", "The window only", "The wooden frame only", "Both of them"],
      correct: 3,
      whyWrong: [
        "The specimen does not treat this as uncovered accidental damage.",
        "The key includes the frame as well.",
        "The glass is also covered.",
        "Correct: both.",
      ],
    },
  },

  // ——— Chapter 4 Property ———
  {
    id: "pr-fire-base",
    chapter: 4,
    section: "Fire and special perils insurance",
    conceptId: "prop-fire",
    title: "Standard fire as the base",
    kind: "definition",
    claim:
      "Unless packaged, a [[standard fire policy]] is the base, extended to [[special perils]] (and sometimes all risks). The proposer chooses the [[sum insured]]; the insurer rates.",
    importance: "core",
    skill: "know",
    sources: [kf(4, "Fire and special perils insurance", "47")],
  },
  {
    id: "pr-unoccupied",
    chapter: 4,
    section: "Fire and special perils insurance",
    conceptId: "prop-fire",
    title: "Unoccupied commercial fire policy restrictions",
    kind: "exclusion",
    claim:
      "When a building becomes unoccupied as defined, cover will normally exclude theft, storm, escape of water and [[malicious damage]] (fire typically remains).",
    importance: "core",
    skill: "know",
    sources: [eg("21", "1.1")],
    mcq: {
      stem: "A building is covered under a fire and special perils insurance policy. When the building becomes unoccupied as defined in the policy, the cover will normally exclude theft, storm, escape of water and which other peril?",
      options: ["Fire", "Flood", "Impact", "Malicious damage"],
      correct: 3,
      whyWrong: [
        "Fire usually remains the core peril.",
        "Flood is not the fourth named exclusion in the specimen.",
        "Impact is not the fourth named exclusion in the specimen.",
        "Correct: malicious damage.",
      ],
    },
  },
  {
    id: "pr-theft-holdup",
    chapter: 4,
    section: "Theft insurance",
    conceptId: "prop-theft",
    title: "Theft and hold-up",
    kind: "definition",
    claim:
      "Theft wordings typically require [[forcible and violent]] entry/exit (to stop people hiding on premises). [[Hold-up]] is theft accompanied by assault. Underinsurance/average commonly applies. First-loss limits are often used.",
    importance: "core",
    skill: "know",
    sources: [kf(4, "Theft insurance", "54–58")],
  },
  {
    id: "pr-money-def",
    chapter: 4,
    section: "Money insurance",
    conceptId: "prop-money",
    title: "What money insurance covers",
    kind: "definition",
    claim:
      "Money insurance is [['all risks']] on money. The specimen definition of money for this class is [[cash, cheques and postage stamps]] (not credit/debit cards in that item). Employee fraud is a [[fidelity / money]] issue: a theft policy does not provide that protection in the specimen comparison.",
    extra:
      "Typical limits differ by situation (e.g. an example of £500 for money left out of a safe on the premises). Credit cards are a noted extension, not standard.",
    importance: "core",
    skill: "know",
    sources: [kf(4, "Money insurance", "59–62"), eg("20", "1.1"), eg("10", "1.1")],
    confusedWith: ["prop-theft"],
    mcq: {
      stem: "Money insurance provides cover for",
      options: [
        "cash, cheques and credit and debit cards",
        "cash, cheques and postage stamps",
        "cash, postage stamps and credit and debit cards",
        "cheques, postage stamps and credit and debit cards",
      ],
      correct: 1,
      whyWrong: [
        "Credit/debit cards are not in the specimen money trio.",
        "Correct.",
        "Omits cheques; includes cards.",
        "Omits cash; includes cards.",
      ],
    },
  },
  {
    id: "pr-money-vs-theft-fraud",
    chapter: 4,
    section: "Money insurance",
    conceptId: "prop-money",
    title: "Employee fraud: money not theft",
    kind: "distinction",
    claim:
      "For theft of money due to employee fraud, [[only the money policy]] (not the theft policy) provides some protection in the specimen comparison.",
    importance: "core",
    skill: "understand",
    sources: [eg("10", "1.1")],
    mcq: {
      stem: "A policyholder is considering both theft and money insurance policies to protect himself against theft of money due to employee fraud. Which of these policies, if either, will provide some protection against this loss?",
      options: ["Both policies", "Only the theft policy", "Only the money policy", "Neither policy"],
      correct: 2,
      whyWrong: [
        "Theft insurance is not the specimen vehicle for employee fraud of money.",
        "Opposite of the key.",
        "Correct.",
        "The money policy does give some protection in the specimen.",
      ],
    },
  },
  {
    id: "pr-glass",
    chapter: 4,
    section: "Glass insurance",
    conceptId: "prop-glass",
    title: "Glass class",
    kind: "cover",
    claim:
      "Glass is not only plate glass; it covers destruction/damage to [[fixed glass]]. Often packaged. Standard practice excludes damage by [[fire, lightning]] (left to the fire policy). Commercial glass claims often use [[approved repairers]] (specimen).",
    importance: "supporting",
    skill: "know",
    sources: [kf(4, "Glass insurance", "58–59")],
  },

  // ——— Chapter 5 Pecuniary ———
  {
    id: "pe-le-purpose",
    chapter: 5,
    section: "Legal expenses insurance",
    conceptId: "pec-legal",
    title: "Purpose of legal expenses",
    kind: "definition",
    claim:
      "Legal expenses insurance indemnifies [[legal costs]] arising from specified disputes. Group/personal sections can include employment, personal, motor and conveyancing. Commercial sections include employment, criminal (including HSWA), property disputes, patents/IP — [[not public liability disputes]] (those belong on liability policies).",
    importance: "core",
    skill: "know",
    sources: [kf(5, "Legal expenses insurance", "63–66"), eg("23", "1.1")],
    mcq: {
      stem: "A commercial legal expenses insurance policy would NOT normally provide cover for",
      options: [
        "employment disputes",
        "patents and copyright disputes",
        "property disputes",
        "public liability disputes",
      ],
      correct: 3,
      whyWrong: [
        "Employment is a listed commercial LE section.",
        "Patents/IP is a listed option.",
        "Property disputes are a listed option (not all insurers).",
        "Correct: public liability disputes are outside commercial LE.",
      ],
    },
  },
  {
    id: "pe-bi-dims",
    chapter: 5,
    section: "Business interruption insurance",
    conceptId: "pec-bi",
    title: "BI has two time dimensions",
    kind: "definition",
    claim:
      "Property covers [[direct material damage]]; BI covers [[consequential loss of income/increased cost of working]]. Cover has the [[maximum indemnity period]] chosen by the insured (from occurrence, for as long as the business is affected up to that maximum) and the [[sum insured]] basis (including declaration-linked). [[Turnover]] is total income from activities.",
    importance: "core",
    skill: "understand",
    sources: [kf(5, "Business interruption insurance", "66–70")],
    prediction: "If fire insurance rebuilds the shop, what still leaves the owner uninsured unless they buy something else?",
  },
  {
    id: "pe-bi-indem-period",
    chapter: 5,
    section: "Basic features",
    conceptId: "pec-bi",
    title: "Indemnity period meaning",
    kind: "definition",
    claim:
      "Under BI, the indemnity period is the period [[for which the policy reimburses the insured in respect of a claim]] (not the waiting excess, not the unexpired policy year alone).",
    importance: "core",
    skill: "know",
    sources: [eg("3", "1.1"), kf(5, "Basic features", "67")],
    mcq: {
      stem: "Under a business interruption insurance policy, the indemnity period is the period of time",
      options: [
        "after the date of any loss which is excluded in calculating the loss",
        "for which the policy must be in force before a claim can be considered",
        "for which the policy reimburses the insured in respect of a claim",
        "from the date of loss to the next renewal date",
      ],
      correct: 2,
      whyWrong: [
        "That describes a time excess/franchise idea, not the indemnity period.",
        "That is a waiting/deferred inception idea.",
        "Correct.",
        "Renewal date does not define the indemnity period.",
      ],
    },
  },
  {
    id: "pe-mdw",
    chapter: 5,
    section: "Material damage warranty",
    conceptId: "pec-bi",
    title: "Material damage proviso",
    kind: "rule",
    claim:
      "Virtually all BI policies require a [[material damage warranty/proviso]]: there must be a valid property (material damage) claim for an insured peril before BI responds.",
    importance: "core",
    skill: "understand",
    sources: [kf(5, "Material damage warranty", "69–70")],
  },
  {
    id: "pe-bi-questions",
    chapter: 5,
    section: "Business interruption insurance",
    conceptId: "pec-bi",
    title: "BI proposal: reaction to a claim",
    kind: "procedure",
    claim:
      "Proposers for [[business interruption]] are usually asked how they would react in the event of a claim (continuity plans) — unlike the other classes in the specimen list.",
    importance: "supporting",
    skill: "know",
    sources: [eg("22", "1.1")],
    mcq: {
      stem: "Under which class of insurance are proposers usually asked questions at the proposal stage regarding how they would react in the event of a claim?",
      options: [
        "Business interruption",
        "Commercial vehicle",
        "Employers’ liability",
        "Public liability",
      ],
      correct: 0,
      whyWrong: [
        "Correct.",
        "Vehicle rating does not centre on post-loss trading reaction.",
        "EL centres on employment/injury, not trading continuity questions.",
        "PL centres on third party hazards.",
      ],
    },
  },

  // ——— Chapter 6 Liability ———
  {
    id: "l-el-comp",
    chapter: 6,
    section: "Employers’ liability insurance",
    conceptId: "el-compulsory",
    title: "EL is compulsory (with motor TPL)",
    kind: "rule",
    claim:
      "Apart from third party motor, [[employers’ liability]] is the other major compulsory class. The Employers’ Liability (Compulsory Insurance) Act [[1969]] (and 1998 Regulations) require cover. 2008 amendment regulations (from 1 October 2008) changed certificate display rules; employers must still provide the certificate to employees and keep records. From April 2012 FCA rules require EL tracing/search participation as described in the key facts.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Employers’ liability insurance", "73–76")],
    prediction: "Besides motor third party, which liability class is compulsory for most UK employers?",
  },
  {
    id: "l-el-injury-only",
    chapter: 6,
    section: "Standard policy cover",
    conceptId: "el-cover",
    title: "EL pays injury not property",
    kind: "cover",
    claim:
      "EL indemnifies the employer’s [[legal liability for bodily injury or disease to employees]] arising out of and in the course of employment in the trade or business. It is the class that provides injury claims but [[NOT property claims]] in the specimen comparison.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Standard policy cover", "76–78"), eg("4", "1.1")],
    confusedWith: ["pl-cover", "products-cover"],
    mcq: {
      stem: "Which class of insurance provides cover for injury claims but NOT property claims?",
      options: [
        "Employers’ liability",
        "Products liability",
        "Public liability",
        "Trustees’ indemnity",
      ],
      correct: 0,
      whyWrong: [
        "Correct: EL is employee injury/disease, not third party property.",
        "Products covers injury and damage caused by products.",
        "Public liability covers injury and property.",
        "Trustees’ indemnity is wrongful-act/financial, not this injury-only class.",
      ],
    },
  },
  {
    id: "l-el-rsi",
    chapter: 6,
    section: "Standard policy cover",
    conceptId: "el-cover",
    title: "RSI example",
    kind: "example",
    claim:
      "A secretary with repetitive strain injury from working conditions that permanently prevents existing employment is compensated under the employer’s [[employers’ liability]] policy, not legal expenses, PI or public liability.",
    importance: "core",
    skill: "apply",
    sources: [eg("25", "1.1"), kf(6, "Legal liability", "76–77")],
    mcq: {
      stem: "A secretary develops repetitive strain injury caused by her working conditions which permanently prevents her from continuing her existing employment. Under which of her employer’s insurance policies could compensation be paid?",
      options: [
        "Employers’ liability",
        "Legal expenses",
        "Professional indemnity",
        "Public liability",
      ],
      correct: 0,
      whyWrong: [
        "Correct: employee injury arising from work.",
        "LE pays legal costs, not EL damages.",
        "PI is professional services to clients.",
        "PL is non-employee third parties.",
      ],
    },
  },
  {
    id: "l-el-employee",
    chapter: 6,
    section: "Definition of employee",
    conceptId: "el-cover",
    title: "Definition of employee",
    kind: "definition",
    claim:
      "An employee is defined as [[any person under a contract of service or apprenticeship]] with the insured (wordings expand this). Injury must arise [[out of and in the course of employment]] and in connection with the [[trade or business]]. Cover is usually [[occurrence]] during the period of insurance for injury/disease caused then.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Definition of employee", "77–78")],
  },
  {
    id: "l-pl",
    chapter: 6,
    section: "Public liability insurance",
    conceptId: "pl-cover",
    title: "Public liability is an open policy",
    kind: "definition",
    claim:
      "Public liability is an [[open policy]]: it covers legal liability for accidental injury and damage to third party property (plus consequential loss flowing from that damage; financial loss without damage is more limited). Typical limits might be [[£2 million]], with [[£10 million]] not uncommon. A hotel insuring third party injury and property claims needs [[public liability]].",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Public liability insurance", "80–84"), eg("34", "1.1")],
    confusedWith: ["el-cover", "products-cover"],
    mcq: {
      stem: "A hotel owner wishing to insure his business against third party injury and property claims is most likely to require insurance covering",
      options: [
        "employers’ liability",
        "professional indemnity",
        "public liability",
        "trustees’ indemnity",
      ],
      correct: 2,
      whyWrong: [
        "EL is employees, not hotel guests/public property.",
        "PI is professional advice.",
        "Correct.",
        "Trustees’ indemnity is governance/wrongful acts.",
      ],
    },
  },
  {
    id: "l-products",
    chapter: 6,
    section: "Product liability insurance",
    conceptId: "products-cover",
    title: "Products liability",
    kind: "cover",
    claim:
      "Products liability covers legal liability for [[bodily injury and property damage caused by products]]. It is often an [[extension to public liability]].",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Product liability insurance", "84–85"), eg("27", "1.1")],
    mcq: {
      stem: "Products liability is often found as an extension to which type of insurance policy?",
      options: [
        "Employers’ liability",
        "Professional indemnity",
        "Public liability",
        "Trustees’ indemnity",
      ],
      correct: 2,
      whyWrong: [
        "EL is employment injury.",
        "PI is professional services, not product extensions.",
        "Correct.",
        "Trustees’ is a D&O-like internal liability.",
      ],
    },
  },
  {
    id: "l-do",
    chapter: 6,
    section: "Directors’ and officers’ D&O",
    conceptId: "do-cover",
    title: "D&O claims-made and who is liable",
    kind: "rule",
    claim:
      "Directors may be [[personally responsible for negligence in running a limited company]]. D&O is typically [['claims made']]. Companies Act / 2004 audit act changes allowed companies to fund defence more readily. Pension Schemes Act 2021 introduced new criminal offences noted in the key facts.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Directors’ and officers’ D&O", "85–88"), eg("24", "1.1")],
    confusedWith: ["pi-cover"],
    mcq: {
      stem: "Who may be held personally responsible for negligence in the running of a limited company?",
      options: [
        "Auditors only",
        "Company directors only",
        "Ordinary shareholders only",
        "Preferential shareholders only",
      ],
      correct: 1,
      whyWrong: [
        "Auditors have their own PI exposure; the specimen key is directors.",
        "Correct.",
        "Shareholders are not personally running the company in this sense.",
        "Same as ordinary shareholders for this item.",
      ],
    },
  },
  {
    id: "l-pi",
    chapter: 6,
    section: "Professional indemnity",
    conceptId: "pi-cover",
    title: "Professional indemnity",
    kind: "cover",
    claim:
      "PI protects a professional against liability for [[professional negligence / wrongful professional services]]. Like D&O it is typically [[claims made]]. An architect’s PI claim is usually settled by [[payment to a third party]] (the client), not by cash to the insured as a first-party benefit.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Professional indemnity", "88–90"), eg("26", "1.1")],
    mcq: {
      stem: "A claim under an architect’s professional indemnity policy is usually settled by",
      options: [
        "a cash payment to the insured",
        "payment to the insured’s contractors",
        "payment to the insurers’ contractor",
        "payment to a third party",
      ],
      correct: 3,
      whyWrong: [
        "PI is third-party liability, not a first-party purse to the architect.",
        "Not the usual settlement description.",
        "Not the usual settlement description.",
        "Correct.",
      ],
    },
  },
  {
    id: "l-trustee",
    chapter: 6,
    section: "Trustee insurance",
    conceptId: "trustee-cover",
    title: "Trustees’ indemnity",
    kind: "cover",
    claim:
      "A charity arranges trustees’ indemnity to protect against claims arising from [[personal liability]] of trustees (wrongful acts in governance), not employee injury or ordinary third party property damage.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Charity trustees", "91–92"), eg("35", "1.1")],
    mcq: {
      stem: "A charity arranges trustees’ indemnity cover in order to protect themselves against claims arising from",
      options: [
        "injury to employees",
        "injury to third parties",
        "personal liability",
        "third party property damage",
      ],
      correct: 2,
      whyWrong: [
        "That is EL.",
        "That is PL.",
        "Correct.",
        "That is PL/property.",
      ],
    },
  },
  {
    id: "l-ew",
    chapter: 6,
    section: "Extended warranties",
    conceptId: "extended-warranty",
    title: "Extended warranty",
    kind: "cover",
    claim:
      "Extended warranty is personal cover for purchasers after the maker’s guarantee. Cover is typically [[free repair or replacement for defect]] after the original guarantee. Specimen: dishwasher defect after guarantee expiry, if paid for, is [[extended warranty]] not household contents, all risks or products liability. Cover often [[commences one year after the premium is paid]]. Typical sum insured example [[£2,500]] per period. Repairs often must be by approved agents.",
    importance: "core",
    skill: "know",
    sources: [kf(6, "Extended warranties", "94"), eg("1", "1.1"), eg("2", "1.1"), eg("36", "1.1")],
    mcq: {
      stem: "Under what type of insurance policy would an individual be able to claim for a defect that occurred with his dishwasher after the original guarantee expired, assuming he paid for such cover?",
      options: ["All risks", "Extended warranty", "Household contents", "Products liability"],
      correct: 1,
      whyWrong: [
        "All risks possessions still do not exist to insure a manufacturer defect after guarantee in this item.",
        "Correct.",
        "Contents does not exist to replace a guarantee for inherent defect in this item.",
        "Products liability is the manufacturer/retailer’s third party liability, not the buyer’s warranty product.",
      ],
    },
  },
  {
    id: "l-ew-incept",
    chapter: 6,
    section: "Extended warranties",
    conceptId: "extended-warranty",
    title: "EW inception delay",
    kind: "rule",
    claim:
      "Under an extended warranty, cover often commences [[one year after the premium is paid]].",
    importance: "core",
    skill: "know",
    sources: [eg("2", "1.1"), kf(6, "Extended warranties", "94")],
    mcq: {
      stem: "Under what type of insurance policy does cover often commence one year after the premium is paid?",
      options: [
        "Business interruption",
        "Directors’ and officers’ liability",
        "Extended warranty",
        "Professional indemnity",
      ],
      correct: 2,
      whyWrong: [
        "BI follows material damage during the policy period.",
        "D&O is claims-made during its period, not a one-year deferred consumer warranty.",
        "Correct.",
        "PI is claims-made professional liability.",
      ],
    },
  },
  {
    id: "l-cyber",
    chapter: 6,
    section: "Cyber insurance",
    conceptId: "cyber-cover",
    title: "Cyber spans classes",
    kind: "definition",
    claim:
      "Cyber insurance [[spans property, pecuniary and liability]]. Traditional policies proved problematic for cyber; dedicated wordings cover first-party (systems, interruption, ransomware as described) and third-party (data/privacy, GDPR/DPA exposures) with important exclusions listed in the key facts.",
    importance: "supporting",
    skill: "know",
    sources: [kf(6, "Cyber insurance", "92–94")],
  },
];

export const CHAPTER_META: Record<
  1 | 2 | 3 | 4 | 5 | 6,
  { title: string; outcome: string; examShare: string }
> = {
  1: { title: "Motor insurance", outcome: "1.1", examShare: "Largest product class inside LO 1 (~36 questions)" },
  2: { title: "Health insurance", outcome: "1.1", examShare: "PA/sickness, medical expenses, travel PA" },
  3: { title: "Package policies", outcome: "1.1", examShare: "Household and commercial packages" },
  4: { title: "Property insurance", outcome: "1.1", examShare: "Fire, theft, glass, money" },
  5: { title: "Pecuniary insurance", outcome: "1.1", examShare: "Legal expenses and business interruption" },
  6: { title: "Liability insurance", outcome: "1.1", examShare: "EL, PL, products, PI, D&O, trustees, EW, cyber" },
};
