import { kf } from "./facts";
import { type AuthoredQuestion } from "./questions";

const q = (row: AuthoredQuestion): AuthoredQuestion => row;

export const QUESTIONS_MORE: AuthoredQuestion[] = [
  q({
    id: "q-loss-of-use",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-loss-of-use"],
    factIds: ["m-loss-of-use"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Under a standard comprehensive private motor policy, loss of use is",
    options: [
      "included automatically with no excess",
      "a specific exclusion, though limited cover or a courtesy car may be arranged",
      "the same as breakdown recovery",
      "paid as a capital sum like personal accident",
    ],
    correct: 1,
    whyCorrect: "Key Facts: loss of use is a comprehensive exclusion; some insurers sell limited per-day cover or provide a replacement vehicle for a limited period.",
    whyWrong: [
      "It is excluded, not automatic.",
      "Correct.",
      "Breakdown is a different optional extra; accident recovery is treated differently again.",
      "PA benefits are a different section.",
    ],
    misconception: "motor-breakdown",
    sources: [kf(1, "Loss of use", "9")],
    examStyle: true,
  }),
  q({
    id: "q-glass-ncd",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-glass", "motor-ncd"],
    factIds: ["m-glass-ncd"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "A comprehensive policy pays only for a broken windscreen. What happens to no claims discount?",
    options: [
      "NCD is always lost",
      "NCD drops back two years",
      "A payment under the glass section alone does not affect NCD",
      "NCD is protected only if the third party is identified",
    ],
    correct: 2,
    whyCorrect: "Glass as a standalone section payment does not affect NCD.",
    whyWrong: [
      "That would be an ordinary damage claim, not glass-alone.",
      "The usual NCD step-back after a claim, not glass-alone.",
      "Correct.",
      "That is the uninsured-driver promise, not glass.",
    ],
    misconception: "motor-ncd",
    sources: [kf(1, "Breakage of glass", "8–9")],
    examStyle: true,
  }),
  q({
    id: "q-specified-moto",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-cycle-specified"],
    factIds: ["m-cycle-specified"],
    difficulty: 2,
    kind: "definition",
    cognitive: "recognition",
    stem: "Specified motorcycle insurance means",
    options: [
      "any motorcycle the insured happens to ride",
      "the driver is insured for a particular motorcycle",
      "cover for accessories even if the machine is not stolen",
      "the same personal accident benefits as a private car",
    ],
    correct: 1,
    whyCorrect: "Key Facts: the single method is specified motorcycle insurance — a particular machine.",
    whyWrong: [
      "That would be closer to ‘driving other cycles’, an optional extra.",
      "Correct.",
      "Motorcycle theft of accessories usually needs the machine stolen too.",
      "Motorcycle comprehensive typically has no PA / medical expenses beyond RTA emergency treatment.",
    ],
    sources: [kf(1, "Motorcycle insurance", "13")],
    examStyle: true,
  }),
  q({
    id: "q-caravan-tp",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-caravans"],
    factIds: ["m-caravans"],
    difficulty: 3,
    kind: "scenario",
    cognitive: "application",
    stem: "A touring caravan is hit while hitched to the insured car. What cover do insurers generally provide under the motor policy?",
    options: [
      "Full comprehensive on the caravan as if it were the car",
      "Third party cover while it is attached",
      "Household buildings cover",
      "Goods in transit",
    ],
    correct: 1,
    whyCorrect: "Third party while attached; wider caravan cover is usually a separate non-motor policy.",
    whyWrong: [
      "Comprehensive on the trailer is not automatic.",
      "Correct.",
      "Buildings cover the house, not a touring caravan on the road.",
      "GIT is cargo, not the caravan itself.",
    ],
    sources: [kf(1, "Caravans and trailers", "11")],
    examStyle: true,
  }),
  q({
    id: "q-pas-not-indemnity",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas-benefit"],
    factIds: ["h-benefit-not-indemnity"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Which statement about personal accident and sickness insurance is correct?",
    options: [
      "It is a contract of indemnity measured by financial loss",
      "It is a benefit policy, but weekly disablement benefit is still kept around normal earnings",
      "Occupation is the main rating factor for the sickness section",
      "It never appears as an add-on to travel, motor or household",
    ],
    correct: 1,
    whyCorrect: "PA/sickness is a benefit contract, not indemnity; weekly benefits are still kept near earnings to avoid staying off work.",
    whyWrong: [
      "That is indemnity, which Key Facts expressly says this is not.",
      "Correct.",
      "Occupation is the main rating factor for the accident element, not sickness.",
      "Key Facts says it is often an add-on to those products.",
    ],
    sources: [kf(2, "Personal accident and sickness", "17–18")],
    examStyle: true,
  }),
  q({
    id: "q-sickness-21",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas-sickness"],
    factIds: ["h-sickness-21"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Sickness cover generally excludes sickness contracted",
    options: [
      "within the first 21 days of the policy",
      "anywhere outside the insured’s home town",
      "after 104 weeks of employment",
      "unless an excess of £1,000 is paid",
    ],
    correct: 0,
    whyCorrect: "The 21-day waiting exclusion stops cover for disease already incubating at inception.",
    whyWrong: [
      "Correct.",
      "Geography is a different limitation.",
      "104 weeks is the usual maximum weekly-benefit period, not an exclusion trigger.",
      "That is a household subsidence-style excess, not PA sickness.",
    ],
    misconception: "health-pas-franchise",
    sources: [kf(2, "Sickness cover", "19")],
    examStyle: true,
  }),
  q({
    id: "q-franchise-vs-excess",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas-franchise"],
    factIds: ["h-sickness-21"],
    difficulty: 4,
    kind: "distinction",
    cognitive: "distinction",
    stem: "A seven-day time franchise on sickness benefit means that if the insured is off for ten days",
    options: [
      "the first seven days are always deducted like an excess",
      "nothing is paid because ten days is still ‘short’",
      "the whole ten days are paid, including the first seven, because the threshold was crossed",
      "only capital benefits are paid",
    ],
    correct: 2,
    whyCorrect: "A franchise is a threshold. Once sickness lasts beyond seven days, the claim includes the initial seven days. An excess would deduct them.",
    whyWrong: [
      "That describes an excess, which Key Facts contrasts with a franchise.",
      "Under seven days would pay nothing; ten days crosses the threshold.",
      "Correct.",
      "This is weekly sickness benefit, not a capital sum.",
    ],
    sources: [kf(2, "Sickness cover", "19")],
    examStyle: true,
  }),
  q({
    id: "q-ptd-delay",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-ptd"],
    factIds: ["h-ptd"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Permanent total disablement compensation may be delayed because",
    options: [
      "the insurer is waiting for the NHS to pay first",
      "it can take 12 or 24 months to know the disablement is permanent and total",
      "ELTO must be notified",
      "a material damage proviso must be satisfied",
    ],
    correct: 1,
    whyCorrect: "Key Facts: PTD capital sum may wait 12 or 24 months to establish permanence and totality.",
    whyWrong: [
      "MEI is about private treatment, not this delay.",
      "Correct.",
      "EL tracing is employers’ liability.",
      "The material damage proviso is business interruption.",
    ],
    sources: [kf(2, "Permanent total disablement", "20")],
    examStyle: true,
  }),
  q({
    id: "q-ppd-not-standard",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-ppd"],
    factIds: ["h-ppd"],
    difficulty: 2,
    kind: "which-correct",
    cognitive: "understanding",
    stem: "Which statement about permanent partial disablement is correct in IF2?",
    options: [
      "It is a standard PA benefit at the same capital sum as PTD",
      "It is not standard; when given it pays for specified parts of limbs at a smaller percentage",
      "It is a weekly benefit for sickness only",
      "It replaces employers’ liability",
    ],
    correct: 1,
    whyCorrect: "PPD is not standard; it is a scheduled-parts benefit when offered.",
    whyWrong: ["PTD is the usual capital benefit, not PPD.", "Correct.", "That is closer to TTD/sickness weekly cover.", "EL is a liability class."],
    sources: [kf(2, "Permanent partial disablement", "20")],
    examStyle: true,
  }),
  q({
    id: "q-tpd-accident",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-tpd"],
    factIds: ["h-tpd"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Temporary partial disablement on a PA/sickness policy typically applies to",
    options: [
      "sickness as well as accident, at 100% of TTD",
      "accident only, traditionally about 40% of the TTD weekly amount",
      "permanent loss of fingers only",
      "private hospital theatre fees",
    ],
    correct: 1,
    whyCorrect: "TPD is accident (not sickness) and is traditionally about 40% of TTD.",
    whyWrong: ["Sickness TPD is not the Key Facts wording.", "Correct.", "That is PPD territory.", "That is medical expenses / MEI."],
    sources: [kf(2, "Temporary partial disablement", "21")],
    examStyle: true,
  }),
  q({
    id: "q-mei",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-mei"],
    factIds: ["h-mei"],
    difficulty: 2,
    kind: "definition",
    cognitive: "recognition",
    stem: "Medical expenses insurance (health care insurance) is primarily designed to",
    options: [
      "pay a weekly wage if the insured cannot work",
      "fund private medical treatment outside the NHS",
      "indemnify employers for employee injury",
      "repair consumer goods after the maker’s guarantee",
    ],
    correct: 1,
    whyCorrect: "MEI is private treatment outside the NHS, including hospital and specialist fees.",
    whyWrong: ["That is PA/sickness weekly benefit.", "Correct.", "That is employers’ liability.", "That is extended warranty."],
    misconception: "health-medexp",
    sources: [kf(2, "Medical expenses insurance", "23")],
    examStyle: true,
  }),
  q({
    id: "q-hh-ad-ext",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-accidental-damage"],
    factIds: ["p-acc-damage"],
    difficulty: 2,
    kind: "scenario",
    cognitive: "application",
    stem: "A householder drills through a water pipe. Which household extension is designed for this kind of mishap?",
    options: [
      "Subsidence, ground heave or landslip",
      "Accidental damage extension",
      "Legal expenses employment cover",
      "Uninsured driver promise",
    ],
    correct: 1,
    whyCorrect: "Key Facts uses drilling through a pipe as the accidental-damage illustration, always with at least a £100 excess.",
    whyWrong: ["A different buildings peril with a large excess.", "Correct.", "Pecuniary legal expenses.", "Motor."],
    sources: [kf(3, "Accidental damage extension", "30")],
    examStyle: true,
  }),
  q({
    id: "q-shop-fabric",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["package-shop"],
    factIds: ["p-shop"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "In shopkeepers’ and hoteliers’ packages, the fabric of the building is generally",
    options: [
      "the main thing the package is designed to cover",
      "insured or rated separately because the package is geared to business contents and liabilities",
      "covered only if the shop is unoccupied",
      "replaced by employers’ liability",
    ],
    correct: 1,
    whyCorrect: "Packages for shops/hotels are geared to the business; building fabric is separate.",
    whyWrong: ["Opposite of the Key Facts point.", "Correct.", "Unoccupancy restricts perils; it does not replace the rating split.", "EL is a liability class."],
    sources: [kf(3, "Commercial insurance", "43")],
    examStyle: true,
  }),
  q({
    id: "q-holdup",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-holdup"],
    factIds: ["pr-holdup"],
    difficulty: 4,
    kind: "scenario",
    cognitive: "application",
    stem: "A thief threatens a cashier with a knife at an unlocked shop door. Cover for this is described in IF2 as",
    options: [
      "standard theft, because there was violence",
      "hold-up — assault or threat to people, whether or not entry was forcible",
      "fidelity, because a staff member was present",
      "public liability, because a visitor might have been hurt",
    ],
    correct: 1,
    whyCorrect: "Hold-up is theft with assault/violence/threat to people, irrespective of forcible entry. Standard theft often needs force and violence to the premises.",
    whyWrong: [
      "Violence to a person is not the same as forcible entry to the building.",
      "Correct.",
      "Fidelity is employee dishonesty.",
      "PL is legal liability to third parties, not the stolen till.",
    ],
    misconception: "prop-theft",
    sources: [kf(4, "Theft insurance", "56")],
    examStyle: true,
  }),
  q({
    id: "q-all-risks-named",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-all-risks"],
    factIds: ["pr-all-risks"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "The structural difference between fire & special perils and all risks material-damage cover is that",
    options: [
      "all risks lists named perils; fire lists accidents",
      "fire & special perils offers a choice of named perils; all risks covers accidental loss/damage subject to exclusions",
      "all risks never has exclusions",
      "fire cover is claims-made",
    ],
    correct: 1,
    whyCorrect: "Named-perils vs accidental loss subject to exclusions is the ABI wording contrast in Key Facts.",
    whyWrong: ["Reversed.", "Correct.", "All risks is still exclusion-driven.", "Fire MD is occurrence/damage, not claims-made."],
    sources: [kf(4, "All risks", "53")],
    examStyle: true,
  }),
  q({
    id: "q-money-7day",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-money-fidelity", "pec-fidelity"],
    factIds: ["pr-money-7day"],
    difficulty: 4,
    kind: "cumulative",
    cognitive: "distinction",
    stem: "Employee theft of money not discovered for two months is generally",
    options: [
      "paid in full under money ‘all risks’",
      "excluded from money (seven-day discovery) and is a fidelity risk",
      "a standard theft (force and violence) claim",
      "products liability",
    ],
    correct: 1,
    whyCorrect: "Money typically excludes employee dishonesty not found within seven days; fidelity is the pecuniary class for staff dishonesty.",
    whyWrong: ["The seven-day discovery exclusion blocks this.", "Correct.", "No forcible entry is described.", "Injury/damage from goods."],
    sources: [kf(4, "Exclusions", "61")],
    examStyle: true,
  }),
  q({
    id: "q-decl-linked",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-bi-declaration"],
    factIds: ["pe-declaration"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "On a declaration-linked business interruption policy the insured",
    options: [
      "must project turnover for the full indemnity period plus a year",
      "estimates the forthcoming year and insurers apply a one-third uplift",
      "needs no sum insured because BI is a benefit policy",
      "is covered only for engineering perils",
    ],
    correct: 1,
    whyCorrect: "Declaration-linked: estimate next year, one-third uplift, avoiding long projections.",
    whyWrong: ["That difficulty is why declaration-linked exists.", "Correct.", "BI is indemnity-style interruption, not PA benefit.", "Engineering is one BI type, not this rating method."],
    sources: [kf(5, "Basis of fixing sums insured", "68")],
    examStyle: true,
  }),
  q({
    id: "q-group-legal-4",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-legal-group-sections"],
    factIds: ["pe-group-sections"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Which four sections can a proposer choose on a group legal benefit policy?",
    options: [
      "Fire, theft, glass, money",
      "Employment, personal, motor, conveyancing",
      "EL, PL, products, D&O",
      "RTA, TPO, TPFT, comprehensive",
    ],
    correct: 1,
    whyCorrect: "Key Facts lists those four group legal sections.",
    whyWrong: ["Property classes.", "Correct.", "Liability classes.", "Motor cover levels."],
    sources: [kf(5, "Group legal benefit policies", "64")],
    examStyle: true,
  }),
  q({
    id: "q-credit-vs-bi",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-credit", "pec-bi"],
    factIds: ["pe-credit"],
    difficulty: 4,
    kind: "cumulative",
    cognitive: "distinction",
    stem: "A manufacturer’s largest customer simply will not pay an undisputed invoice. Which pecuniary class is designed for that?",
    options: [
      "Business interruption after a fire",
      "Credit insurance",
      "Legal expenses motor cover",
      "Household new-for-old",
    ],
    correct: 1,
    whyCorrect: "Credit insurance is trade-debt default. BI needs insured damage; legal expenses is cost of pursuing rights; new-for-old is household settlement.",
    whyWrong: ["BI follows material damage.", "Correct.", "Motor legal expenses is a different section.", "Household settlement basis."],
    sources: [kf(5, "Credit insurance", "63")],
    examStyle: true,
  }),
  q({
    id: "q-elto",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["el-elto"],
    factIds: ["l-elto"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "ELTO is",
    options: [
      "the 1969 compulsory EL statute",
      "the 2011 Employers’ Liability Tracing Office, holding a database of EL policies for claimants",
      "the ABI fire wording",
      "the Green Card Free Circulation Area",
    ],
    correct: 1,
    whyCorrect: "ELTO replaced the 1999 EL service in 2011 as an independent tracing database.",
    whyWrong: ["That Act makes EL compulsory.", "Correct.", "Material damage wording.", "Motor foreign use."],
    sources: [kf(6, "Employers’ liability insurance", "74–75")],
    examStyle: true,
  }),
  q({
    id: "q-ern",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["el-ern"],
    factIds: ["l-ern"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "The employer reference number (ERN) used by ELTO",
    options: [
      "changes every time the employer moves tax office, so historic claims cannot be traced",
      "is unique; the historic ERN for a point in time remains permanent",
      "is the employee’s National Insurance number",
      "is only required for public liability",
    ],
    correct: 1,
    whyCorrect: "ERN is unique and historically stable; insurers must supply it to the ELD.",
    whyWrong: ["Key Facts says the historic ERN remains permanent.", "Correct.", "Different identifier.", "This is an EL tracing requirement."],
    sources: [kf(6, "Employers’ liability insurance", "75")],
    examStyle: true,
  }),
  q({
    id: "q-el-vs-claims-made",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["el-employee", "pi-claims-made"],
    factIds: ["l-employee-def", "l-pi-claims"],
    difficulty: 4,
    kind: "cumulative",
    cognitive: "distinction",
    stem: "Which pairing is consistent with IF2?",
    options: [
      "Employers’ liability is typically claims-made; professional indemnity is occurrence",
      "Employers’ liability typically responds to injury caused during the period (occurrence); professional indemnity is typically claims-made",
      "Both EL and PI ignore when the injury or claim happens",
      "Public liability never covers consequential loss from damaged property",
    ],
    correct: 1,
    whyCorrect: "EL: injury/disease caused during the period. PI (like D&O): claims-made.",
    whyWrong: ["Reversed.", "Correct.", "Timing is the whole distinction.", "PL does cover consequential loss flowing from physical damage."],
    sources: [kf(6, "Period of insurance", "77"), kf(6, "Professional indemnity", "88")],
    examStyle: true,
  }),
  q({
    id: "q-products-agg",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["products-aggregate"],
    factIds: ["l-products-agg"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Product liability wordings usually apply",
    options: [
      "an unlimited indemnity like RTA injury",
      "a yearly aggregate limit to all injury and damage in the period",
      "cover only for the manufacturer, never a retailer",
      "a seven-day time franchise",
    ],
    correct: 1,
    whyCorrect: "Yearly aggregate, often matching the any-one-occurrence figure.",
    whyWrong: ["Injury unlimited is motor RTA, not products.", "Correct.", "Sellers of goods include retailers.", "PA sickness franchise."],
    sources: [kf(6, "Product liability insurance", "82")],
    examStyle: true,
  }),
  q({
    id: "q-pl-financial",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["pl-consequential"],
    factIds: ["l-pl-conseq"],
    difficulty: 4,
    kind: "distinction",
    cognitive: "distinction",
    stem: "A van hits a shopfront. The owner’s lost takings while the window is boarded are, in public liability terms,",
    options: [
      "pure financial loss with no connection to damage, always excluded",
      "consequential loss flowing from physical damage to third-party property, which PL typically covers",
      "business interruption on the van driver’s own BI policy automatically",
      "extended warranty",
    ],
    correct: 1,
    whyCorrect: "PL covers losses directly flowing from insured physical damage (Key Facts even uses hiring another car as an illustration). Pure financial loss without damage is a different, narrower idea.",
    whyWrong: [
      "That would be pure financial loss, not loss following damage.",
      "Correct.",
      "The driver’s BI would need their own insured damage and a material-damage proviso — not this third-party shop.",
      "Consumer goods after guarantee.",
    ],
    sources: [kf(6, "Consequential loss", "80")],
    examStyle: true,
  }),
  q({
    id: "q-travel-10m",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-travel-medical"],
    factIds: ["p-travel-med"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Travel medical expenses in the Key Facts illustration are commonly around",
    options: [
      "£250–£500 as on comprehensive motor",
      "£10 million, with single-trip cover usually limited to about three months",
      "the RTA emergency treatment fee only",
      "new for old on buildings",
    ],
    correct: 1,
    whyCorrect: "£10 million is described as not uncommon; single-trip typically max three months.",
    whyWrong: ["Motor comprehensive medical extras.", "Correct.", "Motor RTA.", "Household settlement."],
    sources: [kf(3, "Travel insurance", "39–40")],
    examStyle: true,
  }),
  q({
    id: "q-el-min-limit",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["el-compulsory"],
    factIds: ["l-el-min-limit"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Following the 1998 Regulations, the statutory minimum employers’ liability limit of indemnity in the IF2 Key Facts is",
    options: ["£2 million", "£5 million", "£10 million", "Unlimited"],
    correct: 1,
    whyCorrect: "1998 Regulations raised the statutory floor from £2 million to £5 million. £10 million is market practice since January 1995.",
    whyWrong: ["Previous statutory floor.", "Correct.", "Practice since 1995, not the statute.", "Motor injury is unlimited; EL is not."],
    sources: [kf(6, "Employers’ liability insurance", "73")],
    examStyle: true,
  }),
  q({
    id: "q-pl-excl-employees",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["pl-cover", "el-cover"],
    factIds: ["l-pl-exclusions", "l-el-injury-only"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "A public liability policy in the IF2 Key Facts excludes injury to employees because that risk is",
    options: [
      "always uninsurable",
      "employers’ liability",
      "extended warranty",
      "business interruption",
    ],
    correct: 1,
    whyCorrect: "PL is an open policy defined by exclusions; injury to employees is listed because EL is the employee-injury class.",
    whyWrong: ["EL insures it, and is compulsory.", "Correct.", "Buyer’s defect cover after a guarantee.", "Trading loss after material damage."],
    misconception: "el-cover",
    sources: [kf(6, "Exclusions", "80"), kf(6, "Standard policy cover", "76–78")],
    examStyle: true,
  }),
  q({
    id: "q-products-when",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["products-cover"],
    factIds: ["l-products-when"],
    difficulty: 4,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "Under products liability as described in IF2, when must the injury or damage occur?",
    options: [
      "When the goods were supplied",
      "During the period of insurance, not necessarily when the goods were supplied",
      "Only when a claim is notified, because products is always claims-made",
      "One year after the premium is paid",
    ],
    correct: 1,
    whyCorrect: "Key Facts: the injury or damage must occur during the period of insurance, not necessarily the supply of goods.",
    whyWrong: ["Supply date is not the trigger here.", "Correct.", "Claims-made is D&O/PI.", "That is the extended-warranty specimen timing."],
    sources: [kf(6, "Standard policy cover", "81")],
    examStyle: true,
  }),
  q({
    id: "q-ew-five",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["extended-warranty"],
    factIds: ["l-ew-term"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Extended warranty, in the IF2 Key Facts, is a time extension of the manufacturer’s usual twelve-month guarantee for free repairs for up to",
    options: ["90 days", "six months", "five years", "the lifetime of the product"],
    correct: 2,
    whyCorrect: "Cover is for free repairs following electrical and mechanical defects for a period of up to five years.",
    whyWrong: ["Too short.", "Too short.", "Correct.", "Not how the Key Facts describe the term."],
    sources: [kf(6, "Extended warranties", "90–91")],
    examStyle: true,
  }),
  q({
    id: "q-do-two",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["do-cover"],
    factIds: ["l-do-two-covers"],
    difficulty: 3,
    kind: "which-correct",
    cognitive: "understanding",
    stem: "Directors’ and officers’ insurance in IF2 has two elements. Which pairing is correct?",
    options: [
      "First-party repair of the company’s plant, and products liability for goods sold",
      "Cover for directors personally when they cannot claim from the company, and cover for the company where it may indemnify them",
      "Employers’ liability for staff, and public liability for visitors",
      "Occurrence cover only, with no claims-made wording",
    ],
    correct: 1,
    whyCorrect: "D&O: personal capacity of directors/officers, plus company reimbursement where the company may indemnify them. Basis of cover is claims-made.",
    whyWrong: ["Those are property / products.", "Correct.", "EL and PL.", "D&O is claims-made."],
    sources: [kf(6, "Standard policy cover", "84")],
    examStyle: true,
  }),
];
