import type { ChapterId, Provenance } from "../engine/types";
import { eg, kf, st } from "./facts";

export type QuestionKind =
  | "knowledge"
  | "definition"
  | "distinction"
  | "scenario"
  | "which-correct"
  | "cumulative";

export type CognitiveDemand = "recognition" | "understanding" | "distinction" | "application";

export type AuthoredQuestion = {
  id: string;
  chapter: ChapterId;
  lo: "1.1";
  conceptIds: string[];
  factIds: string[];
  difficulty: 1 | 2 | 3 | 4 | 5;
  kind: QuestionKind;
  cognitive: CognitiveDemand;
  stem: string;
  options: [string, string, string, string];
  correct: 0 | 1 | 2 | 3;
  whyCorrect: string;
  whyWrong: [string, string, string, string];
  misconception?: string;
  sources: Provenance[];
  examStyle?: boolean;
};

const q = (row: AuthoredQuestion): AuthoredQuestion => row;

export const QUESTIONS: AuthoredQuestion[] = [
  q({
    id: "q-rta-tppd",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-rta"],
    factIds: ["m-rta-tppd"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "What is the Road Traffic Act only limit for third party property damage?",
    options: ["£1.2 million", "£5 million", "£20 million", "Unlimited"],
    correct: 0,
    whyCorrect: "RTA only TPPD is limited to £1.2 million in the IF2 materials.",
    whyWrong: [
      "This is the RTA figure.",
      "About the usual commercial motor TPPD illustration, not RTA.",
      "Usual private TPO TPPD illustration.",
      "Injury indemnity is unlimited, not property damage.",
    ],
    misconception: "motor-tpo",
    sources: [kf(1, "Road Traffic Act only", "5"), st("A1A", "1/3")],
    examStyle: true,
  }),
  q({
    id: "q-tpo-20m",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-tpo", "motor-rta"],
    factIds: ["m-tpo-extras"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Which figure is the usual private-car third party property damage limit under third party only cover, as stated in IF2?",
    options: ["£1.2 million", "£5 million", "£20 million", "Unlimited"],
    correct: 2,
    whyCorrect: "TPO usually grants £20 million TPPD for private cars, far above the £1.2 million RTA minimum.",
    whyWrong: [
      "That is the RTA / compulsory minimum, not typical TPO private-car TPPD.",
      "A commercial motor illustration, not private TPO.",
      "Correct.",
      "Injury is unlimited; property damage is not.",
    ],
    misconception: "motor-rta",
    sources: [kf(1, "Third party only (TPO)", "6"), st("A1B", "1/3")],
    examStyle: true,
  }),
  q({
    id: "q-doc-comp",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-driving-other", "motor-comp"],
    factIds: ["m-doc-third-party"],
    difficulty: 3,
    kind: "scenario",
    cognitive: "application",
    stem: "Ayesha has comprehensive private motor insurance and borrows a neighbour’s car. She damages that car. What cover does IF2 say the driving-other-cars extension gives?",
    options: [
      "Comprehensive own-damage on the borrowed car",
      "Third party only — no cover for damage to the borrowed car",
      "TPFT on the borrowed car",
      "Whatever the neighbour’s policy would have paid",
    ],
    correct: 1,
    whyCorrect: "Driving other cars remains third party only, even on a comprehensive policy; there is no cover for damage to the vehicle being driven.",
    whyWrong: [
      "Comprehensive does not travel with the driver onto someone else’s car for own damage.",
      "Correct.",
      "Fire and theft of the borrowed car is not granted by this extension.",
      "The extension is defined by Ayesha’s policy, not the neighbour’s.",
    ],
    misconception: "motor-comp",
    sources: [st("A1D", "1/4")],
    examStyle: true,
  }),
  q({
    id: "q-ncd-glass",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-ncd"],
    factIds: ["m-glass-ncd"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "A windscreen is replaced under the glass section of a comprehensive motor policy and no other claim is made. What happens to the no claims discount?",
    options: [
      "It is reduced by two years",
      "It is lost entirely",
      "It is unaffected if the claim is under this section alone",
      "It is protected only if a green card was issued",
    ],
    correct: 2,
    whyCorrect: "A claim under the glass section alone does not affect NCD.",
    whyWrong: [
      "Two-year step-back is the usual rule for a general claim, not glass-alone.",
      "Glass-alone does not wipe NCD.",
      "Correct.",
      "Green cards relate to foreign use, not NCD.",
    ],
    sources: [kf(1, "Breakage of glass", "8–9"), st("A2A", "1/5")],
    examStyle: true,
  }),
  q({
    id: "q-hit-run",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-uninsured-promise"],
    factIds: ["m-uninsured-promise"],
    difficulty: 3,
    kind: "scenario",
    cognitive: "application",
    stem: "An uninsured-driver promise usually protects NCD and excess if the other vehicle’s details are given. When does IF2 say it will NOT apply?",
    options: [
      "Where the accident is the insured’s fault",
      "Where the other driver is comprehensively insured",
      "Hit and run / untraced accidents where required details are unavailable",
      "Where the claim is for windscreen glass only",
    ],
    correct: 2,
    whyCorrect: "The promise does not apply to hit and run / untraced accidents because the third-party vehicle details cannot be given.",
    whyWrong: [
      "Fault of the insured is a different coverage question.",
      "If the other driver is insured the promise is not the issue.",
      "Correct.",
      "Glass-alone is an NCD rule, not this promise.",
    ],
    sources: [kf(1, "Uninsured driver promise", "8"), st("A1F", "1/5")],
    examStyle: true,
  }),
  q({
    id: "q-rta-pay-excluded",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-exclusions"],
    factIds: ["m-exclusions-rta-pay"],
    difficulty: 4,
    kind: "which-correct",
    cognitive: "understanding",
    stem: "Which statement about Road Traffic Act claims and policy exclusions is correct in IF2?",
    options: [
      "If the policy excludes the use, the insurer may refuse the innocent third party",
      "The insurer must pay an RTA claim even if the wording excludes it, and may recover from the insured",
      "Exclusions never apply to own-damage claims in Northern Ireland",
      "Unlicensed driving always prevents any payment to third parties",
    ],
    correct: 1,
    whyCorrect: "The Acts protect innocent victims: the insurer pays the RTA claim then may recover from the insured.",
    whyWrong: [
      "The whole point of the RTA overlay is that innocent victims are still paid.",
      "Correct.",
      "Riot/civil commotion in NI is an own-damage market exclusion, not this rule.",
      "RTA payment can still be required; recovery from the insured may follow.",
    ],
    sources: [st("A3", "1/8")],
    examStyle: true,
  }),
  q({
    id: "q-bike-accessories",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-cycle"],
    factIds: ["m-bike"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Under a motorcycle policy, accessories are only covered if stolen",
    options: ["from a locked garage", "from the motorcycle", "using force and violence", "with the motorcycle"],
    correct: 3,
    whyCorrect: "Unlike private cars, motorcycle accessories/spares are covered for theft only if the motorcycle is stolen at the same time.",
    whyWrong: [
      "Garage-only theft of accessories is the private-car idea, not the motorcycle difference.",
      "Stolen from the bike while it remains is not covered under that difference.",
      "Forcible and violent is a commercial theft wording idea.",
      "Correct — stolen with the motorcycle.",
    ],
    examStyle: true,
    sources: [st("B1", "1/9"), eg("8", "1.1")],
  }),
  q({
    id: "q-comm-omit-pa",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-commercial"],
    factIds: ["m-comm-omit"],
    difficulty: 2,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Which cover is omitted from a comprehensive commercial vehicle policy but provided under comprehensive private car insurance?",
    options: ["Foreign use", "Legal costs in defence of a claim", "Personal accident benefits", "Towing of a disabled vehicle"],
    correct: 2,
    whyCorrect: "Personal accident (and other ‘personal benefits’) are omitted from standard commercial motor.",
    whyWrong: [
      "Foreign use is not the omitted personal-benefits class.",
      "Defence costs appear in commercial third party notes.",
      "Correct.",
      "Towing appears in commercial trailer notes.",
    ],
    examStyle: true,
    sources: [st("C1D", "1/11"), eg("9", "1.1")],
  }),
  q({
    id: "q-comm-min-tppd",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-commercial-tppd"],
    factIds: ["m-comm-tppd"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "What is the minimum legal limit of indemnity for third party property damage under a commercial vehicle insurance policy?",
    options: ["£100,000", "£250,000", "£500,000", "£1,200,000"],
    correct: 3,
    whyCorrect: "The specimen key is £1,200,000 — the RTA property-damage minimum also used for restricted haulage limits.",
    whyWrong: ["Too low.", "Too low.", "Too low.", "Correct."],
    examStyle: true,
    sources: [eg("7", "1.1"), st("C1A", "1/11")],
  }),
  q({
    id: "q-git-not-motor",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-commercial"],
    factIds: ["m-comm-scope"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Commercial motor insurance covers risks to the vehicles themselves. Cover for the goods they carry is",
    options: [
      "included automatically on comprehensive commercial motor",
      "a separate class: goods in transit",
      "always added by the loading-and-unloading extension",
      "treated as personal belongings",
    ],
    correct: 1,
    whyCorrect: "Goods carried are goods in transit, not commercial motor.",
    whyWrong: [
      "Comprehensive commercial still concerns the vehicle, not cargo.",
      "Correct.",
      "Loading/unloading is third party injury/damage during those operations, not cargo insurance.",
      "Personal belongings are a different extra.",
    ],
    sources: [kf(1, "Commercial motor insurance", "16"), st("C", "1/10")],
    examStyle: true,
  }),
  q({
    id: "q-sorn",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-compulsory"],
    factIds: ["m-sorn-exam"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "A motor vehicle must be insured unless",
    options: [
      "it is being kept in a garage and not driven on public roads",
      "it is kept on a private driveway and is not driven on public roads",
      "it is only driven on private roads and is not driven on public roads",
      "a Statutory Off Road Notification declaration is made to the DVLA",
    ],
    correct: 3,
    whyCorrect: "The specimen exception is a SORN declaration to the DVLA.",
    whyWrong: [
      "Garage storage is not the specimen exception.",
      "A driveway is not the specimen exception.",
      "Private-road-only use is not the specimen exception.",
      "Correct.",
    ],
    examStyle: true,
    sources: [eg("6", "1.1")],
  }),
  q({
    id: "q-four-levels",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-cover-levels"],
    factIds: ["m-four-levels"],
    difficulty: 1,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Which sequence lists private motor cover from minimum to widest?",
    options: [
      "TPO, RTA only, comprehensive, TPFT",
      "RTA only, TPO, TPFT, comprehensive",
      "TPFT, TPO, RTA only, comprehensive",
      "Comprehensive, TPFT, TPO, RTA only",
    ],
    correct: 1,
    whyCorrect: "RTA only → TPO → TPFT → comprehensive.",
    whyWrong: ["Mis-orders the minimum.", "Correct.", "Starts too high.", "That is widest to narrowest."],
    sources: [kf(1, "Standard policy cover", "5"), st("A1", "1/2")],
    examStyle: true,
  }),
  q({
    id: "q-tpft-vs-comp",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-tpft", "motor-comp"],
    factIds: ["m-comp"],
    difficulty: 2,
    kind: "distinction",
    cognitive: "distinction",
    stem: "What is the main extra that comprehensive private motor adds over TPFT?",
    options: [
      "Third party injury indemnity",
      "Fire, lightning, explosion and theft of the insured’s car",
      "Accidental and malicious damage to the insured’s car",
      "Goods in transit",
    ],
    correct: 2,
    whyCorrect: "Comprehensive adds accidental and malicious own-damage on an all-risks-of-own-damage basis with listed exclusions.",
    whyWrong: [
      "Already in RTA/TPO.",
      "That is the TPFT extra over TPO.",
      "Correct.",
      "Not a motor own-damage extra.",
    ],
    misconception: "motor-tpft",
    sources: [kf(1, "Comprehensive", "7"), st("A1D", "1/4")],
    examStyle: true,
  }),
  q({
    id: "q-young-rate",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-young-drivers"],
    factIds: ["m-young-drivers"],
    difficulty: 3,
    kind: "scenario",
    cognitive: "application",
    stem: "A 22-year-old does not own the family car but is one of the main drivers. How does IF2 say the insurer rates the risk?",
    options: [
      "On the owner-parent’s age and experience",
      "On the young driver’s age and experience",
      "Always as named-driver only with no extra premium",
      "As a commercial goods-carrying vehicle",
    ],
    correct: 1,
    whyCorrect: "If a young person is a main driver, rating follows their age and experience, not the owner’s.",
    whyWrong: [
      "That would understate the risk IF2 describes.",
      "Correct.",
      "Occasional additional drivers may be added for extra premium; a main driver is rated as such.",
      "Irrelevant class.",
    ],
    sources: [kf(1, "Young additional drivers", "9"), st("A2C", "1/5–1/6")],
    examStyle: true,
  }),
  q({
    id: "q-load-unload",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-commercial-loading"],
    factIds: ["m-comm-load"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "Under commercial motor third party cover, accidents during loading or unloading",
    options: [
      "are never covered",
      "are covered, and for the driver or attendant may extend beyond the carriageway",
      "are covered only if goods in transit is also in force",
      "are treated as employers’ liability only",
    ],
    correct: 1,
    whyCorrect: "C1A records loading/unloading third party cover, extending beyond the carriageway for driver/attendant.",
    whyWrong: [
      "Opposite of the text.",
      "Correct.",
      "GIT is cargo; this is third party injury/damage during operations.",
      "EL is employment injury, not this motor third party extension.",
    ],
    sources: [st("C1A", "1/11")],
  }),

  q({
    id: "q-pas-benefit",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas"],
    factIds: ["h-not-indemnity"],
    difficulty: 2,
    kind: "definition",
    cognitive: "understanding",
    stem: "A personal accident and sickness policy is best described as",
    options: [
      "a contract of indemnity measured by financial loss",
      "a benefit policy paying stated sums on named contingencies",
      "a first-loss property policy",
      "a claims-made liability policy",
    ],
    correct: 1,
    whyCorrect: "IF2: it is not indemnity; it is a benefit contract.",
    whyWrong: [
      "The text contrasts PAS with indemnity.",
      "Correct.",
      "Wrong class.",
      "Wrong class.",
    ],
    sources: [kf(2, "Personal accident and sickness insurance", "17")],
    examStyle: true,
  }),
  q({
    id: "q-death-12",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas-benefits"],
    factIds: ["h-death-12"],
    difficulty: 1,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "For a death claim under personal accident insurance, death must usually occur within how many months of the accident?",
    options: ["12 months", "18 months", "24 months", "36 months"],
    correct: 0,
    whyCorrect: "Insurers often stipulate twelve months. (24 months appears as a PTD assessment wait, not the usual death window.)",
    whyWrong: ["Correct.", "Not the usual death window.", "Used for assessing PTD, not the usual death claim window.", "Not the usual death window."],
    examStyle: true,
    sources: [kf(2, "Death", "19"), eg("12", "1.1")],
  }),
  q({
    id: "q-franchise",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas-franchise"],
    factIds: ["h-franchise"],
    difficulty: 4,
    kind: "distinction",
    cognitive: "distinction",
    stem: "How does a seven-day time franchise on sickness benefit differ from an excess?",
    options: [
      "A franchise is always deducted from the settlement; an excess is not",
      "If the threshold is passed, the franchise claim includes the first seven days; an excess is deducted",
      "They are interchangeable terms in IF2",
      "A franchise applies only to capital sums",
    ],
    correct: 1,
    whyCorrect: "Key facts: franchises are thresholds; unlike excesses they are not simply deducted. Beyond seven days the whole period is paid.",
    whyWrong: [
      "That reverses the distinction.",
      "Correct.",
      "IF2 distinguishes them.",
      "The franchise discussed is on weekly sickness benefit.",
    ],
    sources: [kf(2, "Sickness cover", "18–19")],
    examStyle: true,
  }),
  q({
    id: "q-suicide",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas"],
    factIds: ["h-suicide"],
    difficulty: 2,
    kind: "scenario",
    cognitive: "application",
    stem: "A failed suicide attempt causes temporary partial disablement. What benefit is normally payable under PAS?",
    options: ["Medical expenses", "Weekly benefit until recovery", "A lump sum", "No benefit"],
    correct: 3,
    whyCorrect: "Specimen: no benefit is normally payable; self-inflicted injury is a typical exclusion.",
    whyWrong: ["Not the usual PAS response here.", "TTD/TPD is not paid for this excluded cause.", "Capital benefit is not paid for this excluded cause.", "Correct."],
    examStyle: true,
    sources: [eg("18", "1.1"), kf(2, "Exclusions", "22")],
  }),
  q({
    id: "q-medexp-care",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-medexp"],
    factIds: ["h-medexp"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "A medical expenses policy will generally NOT pay the cost of",
    options: ["ambulance fees", "anaesthetist’s fees", "long-term residential care", "surgical dressings"],
    correct: 2,
    whyCorrect: "Long-term residential care is outside general medical expenses cover in the specimen.",
    whyWrong: ["Typical acute cost.", "Typical surgical cost.", "Correct.", "Typical treatment cost."],
    examStyle: true,
    sources: [eg("11", "1.1")],
  }),
  q({
    id: "q-travel-pa",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas-benefits", "hh-travel"],
    factIds: ["h-travel-pa"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Under which section of a travel insurance policy would a fixed benefit be paid?",
    options: ["Medical expenses", "Personal accident", "Personal liability", "Personal possessions"],
    correct: 1,
    whyCorrect: "PA pays a fixed/capital benefit; the others are indemnity or property.",
    whyWrong: ["Reimburses costs.", "Correct.", "Third party indemnity.", "Property."],
    examStyle: true,
    sources: [eg("14", "1.1")],
  }),
  q({
    id: "q-occ-rate",
    chapter: 2,
    lo: "1.1",
    conceptIds: ["health-pas"],
    factIds: ["h-not-indemnity"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "Occupation is the main rating factor for which element of personal accident and sickness insurance?",
    options: ["Sickness only", "The accident element, not sickness", "Medical expenses only", "Travel cancellation only"],
    correct: 1,
    whyCorrect: "Occupation is the main rating factor for the personal accident element, not for sickness; occupations are grouped in four classes.",
    whyWrong: ["Opposite of the key facts.", "Correct.", "PMI is a different product.", "Not PAS rating."],
    sources: [kf(2, "Personal accident and sickness insurance", "17")],
    examStyle: true,
  }),

  q({
    id: "q-new-for-old",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-settlement"],
    factIds: ["p-hh-settle"],
    difficulty: 2,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Under household ‘new for old’ (reinstatement) settlement, the insurer generally pays",
    options: [
      "market value after wear and tear on all items",
      "the full cost of replacing as new, with wear and tear still deducted for some items such as clothing and linen",
      "agreed value only",
      "first loss only",
    ],
    correct: 1,
    whyCorrect: "New for old pays replacement as new; wear and tear may still be deducted for clothing/linen, inadequate sums insured, or older property.",
    whyWrong: [
      "That is indemnity/market value, now rarely chosen.",
      "Correct.",
      "Agreed value is not the household default described.",
      "First loss is a commercial theft idea.",
    ],
    sources: [kf(3, "Household insurance", "25–26")],
    examStyle: true,
  }),
  q({
    id: "q-subsidence-xs",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-buildings"],
    factIds: ["p-subsidence-xs"],
    difficulty: 1,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "What is the normal excess example given for subsidence cover under household buildings?",
    options: ["£250", "£500", "£750", "£1,000"],
    correct: 3,
    whyCorrect: "A substantial excess of £1,000 or more (or a percentage of the sum insured) is always imposed.",
    whyWrong: ["Day-to-day excess territory.", "Still below the usual subsidence example.", "Still below.", "Correct."],
    examStyle: true,
    sources: [kf(3, "Subsidence, ground heave or landslip", "30"), eg("15", "1.1")],
  }),
  q({
    id: "q-coastal",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-buildings"],
    factIds: ["p-coastal"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "A standard household policy for a house near the sea would NOT normally cover damage arising from",
    options: ["coastal erosion", "ground heave", "a hurricane force wind", "tidal flooding"],
    correct: 0,
    whyCorrect: "Coastal erosion is outside normal household cover in the specimen.",
    whyWrong: ["Correct.", "Heave is a listed peril with a large excess.", "Storm/wind is a standard peril.", "Flood family unless excluded."],
    examStyle: true,
    sources: [eg("16", "1.1")],
  }),
  q({
    id: "q-storm-gates",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-storm"],
    factIds: ["p-storm-excl"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "Storm or flood cover under household buildings specifically excludes damage to",
    options: ["the main roof", "gates, fences or hedges", "underground drains", "sanitary ware"],
    correct: 1,
    whyCorrect: "Storm/flood excludes frost, subsidence/heave/landslip, and gates, fences or hedges. An excess always applies.",
    whyWrong: ["Roofs are core storm subject-matter.", "Correct.", "Drains/pipes have their own accidental damage grant.", "Glass/sanitary is another section."],
    sources: [kf(3, "Storm or flood", "27")],
    examStyle: true,
  }),
  q({
    id: "q-allrisks-away",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-all-risks"],
    factIds: ["p-allrisks-away"],
    difficulty: 2,
    kind: "definition",
    cognitive: "understanding",
    stem: "When a commercial policy includes an all risks section, this usually means cover is provided",
    options: ["away from the risk address", "including electrical breakdown", "on an agreed value basis", "with no excess"],
    correct: 0,
    whyCorrect: "Specimen meaning: away from the risk address — not ‘no excess’ or breakdown.",
    whyWrong: ["Correct.", "Breakdown is typically excluded or engineered separately.", "Settlement basis, not the meaning of all risks here.", "Excesses still apply."],
    examStyle: true,
    sources: [eg("19", "1.1")],
  }),
  q({
    id: "q-riot-prop",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-buildings"],
    factIds: ["p-riot-property"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "In certain areas of the UK, riot damage is usually covered under which type of policy?",
    options: ["Money", "Property", "Public liability", "Travel"],
    correct: 1,
    whyCorrect: "Specimen: property.",
    whyWrong: ["Wrong class.", "Correct.", "Third party, not the insured’s riot damage.", "Wrong class."],
    examStyle: true,
    sources: [eg("13", "1.1")],
  }),
  q({
    id: "q-hh-theft-vs-comm",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-theft", "prop-theft"],
    factIds: ["p-theft-act", "pr-theft-force"],
    difficulty: 4,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Which statement correctly distinguishes household theft from typical commercial theft wordings?",
    options: [
      "Both always require forcible and violent entry",
      "Household follows the Theft Act 1968 without a force condition; commercial theft usually requires forcible and violent entry or exit",
      "Commercial theft follows the Theft Act only; household always needs hold-up",
      "Neither ever covers attempted theft",
    ],
    correct: 1,
    whyCorrect: "Household: no special restriction, Theft Act 1968. Commercial: forcible and violent to stop hide-and-walk-out.",
    whyWrong: [
      "Household does not impose that condition in the key facts.",
      "Correct.",
      "Reverses the classes.",
      "Attempted theft is mentioned for household.",
    ],
    misconception: "prop-theft",
    sources: [kf(3, "Theft or attempted theft", "29"), kf(4, "Theft insurance", "54–55")],
    examStyle: true,
  }),
  q({
    id: "q-shop-glass",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["package-commercial"],
    factIds: ["p-shop-glass"],
    difficulty: 2,
    kind: "scenario",
    cognitive: "application",
    stem: "An employee accidentally breaks a shop window and its wooden frame. The commercial policy includes plate glass. What is covered in the specimen?",
    options: ["Neither", "Window only", "Frame only", "Both"],
    correct: 3,
    whyCorrect: "Specimen Q17: both the window and the wooden frame.",
    whyWrong: ["Not the key.", "Incomplete.", "Incomplete.", "Correct."],
    examStyle: true,
    sources: [eg("17", "1.1")],
  }),
  q({
    id: "q-unoccupied-days",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-unoccupied"],
    factIds: ["p-unoccupied-30"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "Household theft, escape of water and similar perils are commonly excluded while the building is unfurnished or unoccupied for more than",
    options: ["7 days", "14 days", "30 or 60 days in the period of insurance", "12 months"],
    correct: 2,
    whyCorrect: "Wordings commonly use 30 or 60 days in any one insurance period.",
    whyWrong: ["Too short for the stated household rule.", "Too short.", "Correct.", "Far longer than the stated period."],
    sources: [kf(3, "Theft or attempted theft", "29")],
    examStyle: true,
  }),
  q({
    id: "q-rebuild-sum",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["hh-buildings"],
    factIds: ["p-buildings-def"],
    difficulty: 2,
    kind: "definition",
    cognitive: "understanding",
    stem: "The buildings sum insured on a household policy should represent",
    options: [
      "market value of the house including land",
      "the rebuilding cost at the time rebuilding is complete",
      "original purchase price",
      "outstanding mortgage only",
    ],
    correct: 1,
    whyCorrect: "Key facts: rebuilding cost when rebuilding is complete.",
    whyWrong: ["Land is not rebuilt.", "Correct.", "Historic price is not the measure.", "Mortgage is not the measure."],
    sources: [kf(3, "Household insurance", "26")],
    examStyle: true,
  }),

  q({
    id: "q-unoccupied-malicious",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-fire"],
    factIds: ["pr-unoccupied"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "When a fire and special perils building becomes unoccupied as defined, cover normally excludes theft, storm, escape of water and which other peril?",
    options: ["Fire", "Flood", "Impact", "Malicious damage"],
    correct: 3,
    whyCorrect: "Specimen: malicious damage. Fire typically remains.",
    whyWrong: ["Fire usually remains.", "Not the fourth named exclusion.", "Not the fourth named exclusion.", "Correct."],
    examStyle: true,
    sources: [eg("21", "1.1")],
  }),
  q({
    id: "q-money-def",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-money"],
    factIds: ["pr-money-def"],
    difficulty: 2,
    kind: "definition",
    cognitive: "recognition",
    stem: "Money insurance provides cover for",
    options: [
      "cash, cheques and credit and debit cards",
      "cash, cheques and postage stamps",
      "cash, postage stamps and credit and debit cards",
      "cheques, postage stamps and credit and debit cards",
    ],
    correct: 1,
    whyCorrect: "Specimen trio: cash, cheques and postage stamps. Cards are a typical extension, not that item’s definition.",
    whyWrong: ["Includes cards.", "Correct.", "Omits cheques.", "Omits cash."],
    examStyle: true,
    sources: [eg("20", "1.1")],
  }),
  q({
    id: "q-money-fraud",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-money", "prop-theft"],
    factIds: ["pr-money-vs-theft-fraud"],
    difficulty: 3,
    kind: "distinction",
    cognitive: "distinction",
    stem: "For theft of money due to employee fraud, which policy provides some protection in the specimen comparison?",
    options: ["Both theft and money", "Only theft", "Only money", "Neither"],
    correct: 2,
    whyCorrect: "Only the money policy in that comparison.",
    whyWrong: ["Theft is not the vehicle.", "Opposite of the key.", "Correct.", "Money does give some protection."],
    examStyle: true,
    misconception: "prop-theft",
    sources: [eg("10", "1.1")],
  }),
  q({
    id: "q-force-why",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-theft"],
    factIds: ["pr-theft-force"],
    difficulty: 3,
    kind: "which-correct",
    cognitive: "understanding",
    stem: "Commercial theft policies usually require forcible and violent entry or exit in order to",
    options: [
      "match the Theft Act 1968 exactly",
      "stop persons hiding on the premises and later walking out with goods",
      "convert theft into hold-up",
      "disapply average",
    ],
    correct: 1,
    whyCorrect: "The key facts state this eliminates hide-and-walk-out theft.",
    whyWrong: [
      "The Theft Act does not always require force.",
      "Correct.",
      "Hold-up is theft accompanied by assault — a different definition.",
      "Average is underinsurance.",
    ],
    sources: [kf(4, "Theft insurance", "54–55")],
    examStyle: true,
  }),
  q({
    id: "q-holdup",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-theft"],
    factIds: ["pr-holdup"],
    difficulty: 2,
    kind: "definition",
    cognitive: "recognition",
    stem: "In theft insurance, hold-up means",
    options: [
      "any theft after hours",
      "theft accompanied by assault",
      "theft of money from a bank night safe",
      "forcible entry without violence to persons",
    ],
    correct: 1,
    whyCorrect: "Hold-up is defined as theft accompanied by assault.",
    whyWrong: ["Too wide.", "Correct.", "A money-situation, not the definition.", "Force to property is the entry condition, not hold-up."],
    sources: [kf(4, "Theft insurance", "55")],
    examStyle: true,
  }),
  q({
    id: "q-glass-fire-excl",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-glass"],
    factIds: ["pr-glass-fire"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "A standalone glass policy standardly excludes damage caused by",
    options: ["accidental breakage", "malicious damage", "fire and lightning", "impact by a vehicle"],
    correct: 2,
    whyCorrect: "Fire and lightning are left to the fire policy.",
    whyWrong: ["Accidental breakage is the class.", "Not the standard fire-policy carve-out.", "Correct.", "Not the stated standard exclusion."],
    sources: [kf(4, "Glass insurance", "58–59")],
    examStyle: true,
  }),
  q({
    id: "q-money-500",
    chapter: 4,
    lo: "1.1",
    conceptIds: ["prop-money"],
    factIds: ["pr-money-limits"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "The key facts give which example limit for money left out of a safe on the business premises?",
    options: ["£50", "£500", "£5,000", "Unlimited"],
    correct: 1,
    whyCorrect: "An example of £500 is stated for money left out of a safe on the premises.",
    whyWrong: ["Too low for the stated example.", "Correct.", "A different situation would use other limits.", "Money is limited by situation."],
    sources: [kf(4, "Limits of liability", "62")],
    examStyle: true,
  }),

  q({
    id: "q-le-not-pl",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-legal"],
    factIds: ["pe-le-purpose"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "A commercial legal expenses policy would NOT normally provide cover for",
    options: ["employment disputes", "patents and copyright disputes", "property disputes", "public liability disputes"],
    correct: 3,
    whyCorrect: "PL disputes belong on liability policies, not commercial LE.",
    whyWrong: ["Listed LE section.", "Listed option.", "Listed option (not all insurers).", "Correct."],
    examStyle: true,
    sources: [eg("23", "1.1"), kf(5, "Commercial legal protection policies", "64–66")],
  }),
  q({
    id: "q-bi-period",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-bi"],
    factIds: ["pe-bi-indem-period"],
    difficulty: 2,
    kind: "definition",
    cognitive: "understanding",
    stem: "Under business interruption insurance, the indemnity period is the period",
    options: [
      "after the date of any loss which is excluded in calculating the loss",
      "for which the policy must be in force before a claim can be considered",
      "for which the policy reimburses the insured in respect of a claim",
      "from the date of loss to the next renewal date",
    ],
    correct: 2,
    whyCorrect: "Specimen: the period for which the policy reimburses the insured.",
    whyWrong: ["Time excess idea.", "Deferred inception idea.", "Correct.", "Renewal does not define it."],
    examStyle: true,
    sources: [eg("3", "1.1")],
  }),
  q({
    id: "q-mdw",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-bi"],
    factIds: ["pe-mdw"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "A material damage warranty/proviso on a BI policy means",
    options: [
      "BI pays even if the buildings policy is void",
      "there must be a valid property (material damage) claim for an insured peril before BI responds",
      "stock must be valued weekly",
      "EL must be in force",
    ],
    correct: 1,
    whyCorrect: "Virtually all BI policies require a valid material damage claim first.",
    whyWrong: ["Opposite.", "Correct.", "Unrelated.", "Unrelated class."],
    sources: [kf(5, "Material damage warranty", "69–70")],
    examStyle: true,
  }),
  q({
    id: "q-bi-react",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-bi"],
    factIds: ["pe-bi-questions"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Proposers are usually asked how they would react if a claim occurred under which class?",
    options: ["Business interruption", "Commercial vehicle", "Employers’ liability", "Public liability"],
    correct: 0,
    whyCorrect: "Specimen Q22: business interruption (continuity).",
    whyWrong: ["Correct.", "Not centred on trading reaction.", "Employment injury.", "Third party hazards."],
    examStyle: true,
    sources: [eg("22", "1.1")],
  }),
  q({
    id: "q-fines",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-legal"],
    factIds: ["pe-comm-legal"],
    difficulty: 4,
    kind: "which-correct",
    cognitive: "understanding",
    stem: "Commercial legal protection for criminal prosecution defence typically covers",
    options: [
      "fines imposed on the company",
      "defence costs (e.g. under HSWA), but not fines, because paying fines is against the public interest",
      "public liability damages",
      "the cost of rebuilding after fire",
    ],
    correct: 1,
    whyCorrect: "Key facts: costs, including an employee appearing in court, but not fines.",
    whyWrong: ["Fines are not insured.", "Correct.", "That is PL, which LE excludes as disputes.", "Property, not LE."],
    sources: [kf(5, "Commercial legal protection policies", "65")],
    examStyle: true,
  }),
  q({
    id: "q-group-conv",
    chapter: 5,
    lo: "1.1",
    conceptIds: ["pec-legal-group"],
    factIds: ["pe-group-legal"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Conveyancing cover under a group legal benefit policy is for",
    options: [
      "defending HSWA prosecutions",
      "legal costs of buying and/or selling one’s house up to a specified limit",
      "patents and copyright",
      "employers’ liability injury claims",
    ],
    correct: 1,
    whyCorrect: "Group legal sections include conveyancing for house sale/purchase costs.",
    whyWrong: ["Commercial criminal section.", "Correct.", "Commercial IP option.", "EL."],
    sources: [kf(5, "Group legal benefit policies", "64")],
  }),

  q({
    id: "q-el-injury",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["el-cover"],
    factIds: ["l-el-injury-only"],
    difficulty: 2,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Which class provides cover for injury claims but NOT property claims?",
    options: ["Employers’ liability", "Products liability", "Public liability", "Trustees’ indemnity"],
    correct: 0,
    whyCorrect: "EL is employee injury/disease, not third party property.",
    whyWrong: ["Correct.", "Products covers injury and damage caused by products.", "PL covers injury and property.", "Wrongful-act financial/governance."],
    examStyle: true,
    sources: [eg("4", "1.1")],
  }),
  q({
    id: "q-rsi",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["el-cover"],
    factIds: ["l-el-rsi"],
    difficulty: 2,
    kind: "scenario",
    cognitive: "application",
    stem: "A secretary develops RSI from working conditions which permanently prevents her existing employment. Which employer policy could pay compensation?",
    options: ["Employers’ liability", "Legal expenses", "Professional indemnity", "Public liability"],
    correct: 0,
    whyCorrect: "Employee injury arising out of work is EL.",
    whyWrong: ["Correct.", "LE pays legal costs.", "PI is professional services to clients.", "PL is non-employee third parties."],
    examStyle: true,
    sources: [eg("25", "1.1")],
  }),
  q({
    id: "q-hotel-pl",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["pl-cover"],
    factIds: ["l-pl"],
    difficulty: 2,
    kind: "scenario",
    cognitive: "application",
    stem: "A hotel owner wants cover for third party injury and property claims. Which class is most likely required?",
    options: ["Employers’ liability", "Professional indemnity", "Public liability", "Trustees’ indemnity"],
    correct: 2,
    whyCorrect: "Guests and public property damage are PL. Employees would be EL separately.",
    whyWrong: ["Employees, not guests.", "Advice to clients.", "Correct.", "Governance."],
    examStyle: true,
    sources: [eg("34", "1.1")],
  }),
  q({
    id: "q-products-ext",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["products-cover"],
    factIds: ["l-products"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Products liability is often found as an extension to which policy?",
    options: ["Employers’ liability", "Professional indemnity", "Public liability", "Trustees’ indemnity"],
    correct: 2,
    whyCorrect: "Specimen: extension to public liability.",
    whyWrong: ["Employment injury.", "Professional services.", "Correct.", "Trustees."],
    examStyle: true,
    sources: [eg("27", "1.1")],
  }),
  q({
    id: "q-directors",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["do-cover"],
    factIds: ["l-do"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Who may be held personally responsible for negligence in the running of a limited company?",
    options: ["Auditors only", "Company directors only", "Ordinary shareholders only", "Preferential shareholders only"],
    correct: 1,
    whyCorrect: "Specimen key: company directors.",
    whyWrong: ["Own PI exposure; not this key.", "Correct.", "Not running the company in this sense.", "Same as ordinary shareholders here."],
    examStyle: true,
    sources: [eg("24", "1.1")],
  }),
  q({
    id: "q-pi-settle",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["pi-cover"],
    factIds: ["l-pi"],
    difficulty: 3,
    kind: "knowledge",
    cognitive: "understanding",
    stem: "A claim under an architect’s professional indemnity policy is usually settled by",
    options: [
      "a cash payment to the insured",
      "payment to the insured’s contractors",
      "payment to the insurers’ contractor",
      "payment to a third party",
    ],
    correct: 3,
    whyCorrect: "PI is third-party liability — typically payment to the client, not a first-party purse to the architect.",
    whyWrong: ["Not first-party.", "Not the usual description.", "Not the usual description.", "Correct."],
    examStyle: true,
    sources: [eg("26", "1.1")],
  }),
  q({
    id: "q-trustee",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["trustee-cover"],
    factIds: ["l-trustee"],
    difficulty: 2,
    kind: "scenario",
    cognitive: "application",
    stem: "A charity buys trustees’ indemnity to protect against claims arising from",
    options: ["injury to employees", "injury to third parties", "personal liability", "third party property damage"],
    correct: 2,
    whyCorrect: "Specimen: personal liability of trustees (wrongful acts), not EL/PL.",
    whyWrong: ["EL.", "PL.", "Correct.", "PL/property."],
    examStyle: true,
    sources: [eg("35", "1.1")],
  }),
  q({
    id: "q-ew-dishwasher",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["extended-warranty"],
    factIds: ["l-ew"],
    difficulty: 2,
    kind: "scenario",
    cognitive: "application",
    stem: "After a dishwasher’s original guarantee expires, the owner paid for extra defect cover. Which product responds?",
    options: ["All risks", "Extended warranty", "Household contents", "Products liability"],
    correct: 1,
    whyCorrect: "Specimen Q1: extended warranty, not contents or the manufacturer’s products liability.",
    whyWrong: ["Not this defect-after-guarantee product.", "Correct.", "Contents does not replace a guarantee for inherent defect here.", "The manufacturer/retailer’s third party liability, not the buyer’s warranty."],
    examStyle: true,
    sources: [eg("1", "1.1"), kf(6, "Extended warranties", "94")],
  }),
  q({
    id: "q-ew-year",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["extended-warranty"],
    factIds: ["l-ew-incept"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "Under what type of policy does cover often commence one year after the premium is paid?",
    options: ["Business interruption", "Directors’ and officers’ liability", "Extended warranty", "Professional indemnity"],
    correct: 2,
    whyCorrect: "Specimen Q2: extended warranty, after the maker’s guarantee year.",
    whyWrong: ["Follows MD during the period.", "Claims-made during its period.", "Correct.", "Claims-made PI."],
    examStyle: true,
    sources: [eg("2", "1.1")],
  }),
  q({
    id: "q-claims-made",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["do-cover", "el-cover"],
    factIds: ["l-claims-made", "l-el-occurrence"],
    difficulty: 4,
    kind: "distinction",
    cognitive: "distinction",
    stem: "Which pair correctly matches trigger to class as described in IF2?",
    options: [
      "EL — claims made; D&O — occurrence",
      "EL — typically occurrence (caused during the period); D&O and PI — typically claims made",
      "Public liability — claims made only; products — occurrence only",
      "Extended warranty — claims made",
    ],
    correct: 1,
    whyCorrect: "EL: injury/disease caused during the period. D&O/PI: claims made.",
    whyWrong: ["Reversed.", "Correct.", "Not the IF2 pairing asked here.", "EW is a consumer defect product after a guarantee, not this trigger pair."],
    misconception: "el-cover",
    sources: [kf(6, "Period of insurance", "78"), kf(6, "Standard policy cover", "86–88")],
    examStyle: true,
  }),
  q({
    id: "q-pl-conseq",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["pl-cover"],
    factIds: ["l-pl-conseq"],
    difficulty: 4,
    kind: "which-correct",
    cognitive: "understanding",
    stem: "Which statement about public liability is correct in IF2?",
    options: [
      "It never covers any financial loss",
      "It covers physical injury/damage and consequential loss flowing from that damage; pure financial loss without damage is more limited",
      "It is the class that excludes all property claims",
      "It is compulsory for all UK employers in the same way as EL",
    ],
    correct: 1,
    whyCorrect: "PL includes consequential loss from insured damage (e.g. hire car) but is not a pure financial-loss policy.",
    whyWrong: [
      "Consequential loss from damage is covered.",
      "Correct.",
      "That is closer to EL’s injury-not-property point.",
      "EL (and motor TPL) are the major compulsory classes described.",
    ],
    sources: [kf(6, "Consequential loss / Financial loss", "81–82")],
    examStyle: true,
  }),
  q({
    id: "q-cum-el-pl-guest",
    chapter: 6,
    lo: "1.1",
    conceptIds: ["el-cover", "pl-cover"],
    factIds: ["l-el-injury-only", "l-pl"],
    difficulty: 3,
    kind: "cumulative",
    cognitive: "application",
    stem: "A hotel chef burns a guest and, separately, a waiter (employee). Which pairing matches IF2?",
    options: [
      "Guest — EL; waiter — PL",
      "Guest — PL; waiter — EL",
      "Both — products liability",
      "Both — professional indemnity",
    ],
    correct: 1,
    whyCorrect: "Guests are third parties (PL). Employees injured arising out of work are EL.",
    whyWrong: ["Reversed.", "Correct.", "Not a product defect.", "Not professional advice."],
    sources: [kf(6, "Public liability insurance", "80"), kf(6, "Employers’ liability insurance", "76")],
    examStyle: true,
  }),
  q({
    id: "q-cum-ew-vs-contents",
    chapter: 3,
    lo: "1.1",
    conceptIds: ["extended-warranty", "hh-contents"],
    factIds: ["l-ew", "p-contents"],
    difficulty: 3,
    kind: "cumulative",
    cognitive: "distinction",
    stem: "Henry’s TV fails after 14 months. He bought extra cover for defects after the shop guarantee. The claim is considered under",
    options: ["All risks", "Extended warranty", "Legal expenses", "Products liability"],
    correct: 1,
    whyCorrect: "Specimen Q36: extended warranty, not household all risks or the seller’s products liability.",
    whyWrong: ["Possessions all risks is not this defect product.", "Correct.", "Costs of disputes, not the repair product.", "Manufacturer/retailer liability."],
    examStyle: true,
    sources: [eg("36", "1.1")],
  }),
  q({
    id: "q-inexperienced",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-comp"],
    factIds: ["m-young-excess"],
    difficulty: 3,
    kind: "definition",
    cognitive: "understanding",
    stem: "For the extra ‘young or inexperienced drivers’ excess, IF2 treats ‘inexperienced’ as",
    options: [
      "any driver under 40",
      "holding a provisional licence, or not having held a full licence for at least a year",
      "anyone without a no claims discount",
      "any additional named driver",
    ],
    correct: 1,
    whyCorrect: "Study text: provisional licence, or not having held a full licence for at least a year. The extra excess sits over any policy excess.",
    whyWrong: ["Not the definition.", "Correct.", "NCD is separate.", "Named drivers are not automatically ‘inexperienced’."],
    sources: [st("A1D", "1/4")],
    examStyle: true,
  }),
  q({
    id: "q-ncd-stepback",
    chapter: 1,
    lo: "1.1",
    conceptIds: ["motor-ncd"],
    factIds: ["m-ncd"],
    difficulty: 2,
    kind: "knowledge",
    cognitive: "recognition",
    stem: "After a claim, insurers generally reduce NCD entitlement by",
    options: ["one week", "dropping back two years", "cancelling the policy", "doubling the excess only"],
    correct: 1,
    whyCorrect: "Generally drop back two years if a claim is made, unless protected.",
    whyWrong: ["Not the stated step-back.", "Correct.", "Not the NCD rule.", "Excess is a different lever."],
    sources: [kf(1, "No claims discount (NCD)", "8"), st("A1E", "1/5")],
    examStyle: true,
  }),
];
